#!/bin/sh
fw=`echo $@ | awk '{print $1}'`;
cd /var/www/html/des20/
git commit -am"changing to $fw" && git checkout $fw
cd /pace/
git commit -am"changing to $fw" && git checkout $fw
cd /TopStor/
git commit -am"changing to $fw" && git checkout $fw


