#! /usr/local/bin/zsh
pp=`echo  $@ | awk '{print $1}'`;
tun=`echo  $@ | awk '{print $2}'`;
oldstamp=0;
# packet : sender stamp command
while true;
do
 readthis=`nc -l $tun $pp;`
 stamp=`echo $readthis | grep awk '{print $2}'`;
 newpcom=`echo $readthis | awk '{$1=$2="";substr($0,3)}'`
 if [[ $newcom == "finish" ]]; then pcom=0; break; fi
 if [[ $stamp != $oldstamp ]];
 then
  oldstamp=$stamp;
  ./runthis $sender $newcom; 
 if 
done
