#! /usr/local/bin/zsh
cd /TopStor
pp=`echo  $@ | awk '{print $1}'`;
tun=`echo  $@ | awk '{print $2}'`;
replier=`echo  $@ | awk '{print $3}'`;
pp=$((pp+1));
oldstamp=0;
# packet : sender stamp command
while true;
do
 readthis=`nc -ld $tun $pp`
 newsender=`echo $readthis | awk '{print $1}'`;
 stamp=`echo $readthis | awk '{print $2}'`;
 newcom=`echo $readthis | awk '{$1=$2="";print substr($0,3)}'`
 echo hi > ask1
 if [[ $newcom == "finish" ]]; then break; fi
 if [[ $newcom == "reply" ]]; then echo $newsender:$newcom > txt/remtereply; fi
 if [[ $stamp != $oldstamp ]];
 then 
  echo hihi > ask1
  oldstamp=$stamp;
  issender=`cat txt/sender | grep "$newsender"`; 
  if [[ $? -eq 0 ]]; 
  then
   echo hihihi > ask1
   sendertun=`echo $issender | awk '{print $3}'`
   senderpp=`echo $issender | awk '{print $4}'`
   ./runthis $sendertun $newsender $replier $senderpp $newcom;
  fi
 fi 
done
