#!/usr/local/bin/zsh
web="/usr/local/www/apache24/data/des19";
loc=`echo $@ | awk '{print $1}'`;
disks=(`/sbin/sysctl kern.disks | sed -e 's/cd0 //g' -e 's/ada0//g' -e 's/kern.disks: //g'`);
noofdisks=` echo $disks | wc -w | awk '{print $1}'`;
onedisk=` cat onedisk.txt`;
xonedisk=`diskinfo -v $onedisk | sed -n -e 3p | awk '{print $1}'`;
sizeonedisk=$(($xonedisk/1024/1024/1024));
size=0;
for disk in  $disks
do
x=`diskinfo -v $disk | sed -n -e 3p | awk '{print $1}'`;
y=$(($x/1024/1024/1024));
size=$(($size+$y));
done
jsonsize=`/usr/local/bin/zsh jsonthis3.sh size $size count $noofdisks onedisk $sizeonedisk R10 97.9 R5 147 R6 97.7 R7 49`;
echo $jsonsize > $web/$loc;

