#!/usr/local/bin/zsh
web='/usr/local/www/apache24/data/des19/Data/'$0'status.log';
logging='/usr/local/www/apache24/data/des19/Data/currentinfo2.log';
domain=`echo $@ | awk '{ print $1 }' `;
domc=`echo $domain | tr '[:lower:]' '[:upper:]'`;
doms=`echo $domain | tr '[:upper:]' '[:lower:]'`;
domshort=` echo $domc | awk -F. '{ print $1 }'`;
admin=`echo $@ | awk '{ print $2 }'`;
pass=`echo $@ | awk '{ print $3 }'`;
domcont=` echo $@ | awk '{ print $4 }'`
userreq=` echo $@ | awk '{ print $5 }'`;
privilege="Active_Directory";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == "true" ]];
then
echo contrun $contrun
domcontip=` host $domcont.$doms | awk '{print $NF}'`
ip1=` echo $domcontip | awk -F. '{print $1}'`;
ip2=` echo $domcontip | awk -F. '{print $2}'`;
ip3=` echo $domcontip | awk -F. '{print $3}'`;
ip4=` echo $domcontip | awk -F. '{print $4}'`;
echo Domain1000:$domain > $web;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Domain_change:'$domain;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info data $logdata user $userreq code Domain1003@@@$domain`;
echo Domain1003@$datenow@$timenow@$domain > ${logging}2 
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
echo $pass > txt/pass;
hostn=`hostname | awk -F. '{print $1}'`;
sed "1s/.*/hostname=\"$hostn\.$doms\"/" /etc/rc.conf > txt/rc.conf;
hostname $hostn.$doms;
cp txt/rc.conf /etc/rc.conf;
/usr/bin/sed -e "s/DOMSMALL/${doms}/g" -e "s/DOMIPCONT/$ip1\.$ip2\.$ip3\.$ip4/g" dhclient.conf > txt/dhclient.conf 2>txt/err.txt
cp txt/dhclient.conf /etc/dhclient.conf
#echo search_domains=\"$doms\" > txt/resolvconf.conf
#echo "domain $doms" >> txt/resolvconf.conf
#echo name_servers=\"$domcontip\" >> txt/resolvconf.conf
#cat /etc/resolv.conf >> txt/resolv.conf;
#cp txt/resolvconf.conf /etc/resolvconf.conf;
#resolvconf -u;
sed -e "s/CONT/$domcont/g" -e "s/DOMSMALL/$doms/g" -e "s/DOMC/$domc/g" -e "s/DOMSH/$domshort/g" -e "s/DOMIPCONT/$ip1\.$ip2\.$ip3\.$ip4/g" smb4.conf > txt/smb4.conf 2>txt/err.txt ; 
cat CIFSshares.txt >> txt/smb4.conf;
cp txt/smb4.conf /usr/local/etc/smb4.conf;
sed -e "s/DOMC/$domc/g" -e "s/DOMSMALL/$doms/g" -e "s/DOMSH/$domshort/g" -e "s/CONT/$domcont/g" krb5.conf > txt/krb5.conf;
cp txt/krb5.conf /etc/ ;
sed -e "s/CONT/$domcont\.$doms/g" -e "s/DOMSMALL/$doms/g" ntp.conf > txt/ntp.conf ;
service samba_server restart;
cp txt/ntp.conf /etc/
service ntpd stop;
service ntpdate restart;
/usr/local/bin/net ads join  -U $admin%$pass > txt/${0:2}$userreq.txt ;
err=`cat  txt/${0:2}$userreq.txt | grep Failed | wc -c `;
if [ $err -ge  4  ]; then
	echo Domain1001:$domain > $web;
	cat txt/${0:2}$userreq.txt > ${web}internal;
	logdata='failed_changing_domain:'$domain;
        code='Domain1004@@@'$domain
echo Domain1004@$datenow@$timenow@$domain > ${logging}2 
else 
 echo Domain1002:$domain > $web; 
 logdata='success_changing_domain:'$domain;
 code='Domain1005@@@'$domain
echo Domain1005@$datenow@$timenow@$domain > ${logging}2 
fi;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info data $logdata user $userreq code $code`;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
fi
