#!/usr/local/bin/zsh
web='/usr/local/www/apache24/data/des19/Data/DomainChangestatus.log';
logging='/usr/local/www/apache24/data/des19/Data/currentinfo2.log';
domain=`echo $@ | awk '{ print $1 }' `;
domc=`echo $domain | tr '[:lower:]' '[:upper:]'`;
doms=`echo $domain | tr '[:upper:]' '[:lower:]'`;
domshort=` echo $domc | awk -F. '{ print $1 }'`;
admin=`echo $@ | awk '{ print $2 }'`;
pass=`echo $@ | awk '{ print $3 }'`;
domcont=` echo $@ | awk '{ print $4 }'`
userreq=` echo $@ | awk '{ print $5 }'`;
privilege="Active_Directory";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == "true" ]];
then
echo contrun $contrun
domcontip='127.0.0.1' 
ip1=` echo $domcontip | awk -F. '{print $1}'`;
ip2=` echo $domcontip | awk -F. '{print $2}'`;
ip3=` echo $domcontip | awk -F. '{print $3}'`;
ip4=` echo $domcontip | awk -F. '{print $4}'`;
echo Domain1010:$domain > $web;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Domain_change:'$domain;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info data $logdata user $userreq code Domain1012@@@$domain`;
echo Domain1012@$datenow@$timenow@$domain > ${logging}2 
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
echo $pass > txt/pass;
hostn=`hostname | awk -F. '{print $1}'`;
hostnc=`echo $hostn | tr '[:lower:]' '[:upper:]'`;
sed "1s/.*/hostname=\"$hostn\.$doms\"/" /etc/rc.conf > txt/rc.conf;
hostname $hostn.$doms;
cp txt/rc.conf /etc/rc.conf;
#/usr/bin/sed -e "s/DOMSMALL/${doms}/g" -e "s/DOMIPCONT/$ip1\.$ip2\.$ip3\.$ip4/g" dhclient.conf > txt/dhclient.conf 2>txt/err.txt
#cp txt/dhclient.conf /etc/dhclient.conf
#echo search_domains=\"$doms\" > txt/resolvconf.conf
#echo "domain $doms" >> txt/resolvconf.conf
#echo name_servers=\"$domcontip\" >> txt/resolvconf.conf
#cat /etc/resolv.conf >> txt/resolv.conf;
#cp txt/resolvconf.conf /etc/resolvconf.conf;
#resolvconf -u;
sed -e "s/CONT/$domcont/g" -e "s/DOMSMALL/$doms/g" -e "s/DOMC/$domc/g" -e "s/DOMSH/$domshort/g" -e "s/MYNAME/$hostnc/g"-e "s/DOMIPCONT/$ip1\.$ip2\.$ip3\.$ip4/g" smb4.confWorkgrp > txt/smb4.conf 2>txt/err.txt ; 
cat CIFSshares.txt >> txt/smb4.conf;
cp txt/smb4.conf /usr/local/etc/smb4.conf;
hostip=`ifconfig em1 | grep "inet " | awk '{print $2}'`
hosts=`cat /etc/hosts | grep -v "$hostn"`;
echo $hosts > /etc/hosts
echo $hostip   $hostn >> /etc/hosts
echo $hostip   $hostn.$doms >> /etc/hosts
#sed -e "s/DOMC/$domc/g" -e "s/DOMSMALL/$doms/g" -e "s/DOMSH/$domshort/g" -e "s/CONT/$domcont/g" krb5.conf > txt/krb5.conf;
#cp txt/krb5.conf /etc/ ;
service samba_server restart;
echo Domain1011:$domain  > $web;
logdata='success_changing_Wrokgroup:'$domain;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info data $logdata user $userreq code Domain1013@@@$domain`;
echo Domain1013@$datenow@$timenow@$domain > ${logging}2 
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
fi
