#!/usr/local/bin/zsh
cd /TopStor/
web='/var/www/html/des20/Data/'`basename $0`'status.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
txtres='/TopStordata/'`basename $0`'.txt'
rm -rf $txtres &>/dev/null
glog='/TopStordata/TopStor.log';
domain=`echo $@ | awk '{ print $1 }' `;
domc=`echo $domain | tr '[:lower:]' '[:upper:]'`;
doms=`echo $domain | tr '[:upper:]' '[:lower:]'`;
domshort=` echo $domc | awk -F. '{ print $1 }'`;
admin=`echo $@ | awk '{ print $2 }'`;
pass=`echo $@ | awk '{ print $3 }'`;
domcont=` echo $@ | awk '{ print $4 }'`
userreq=` echo $@ | awk '{ print $5 }'`;
privilege="Active_Directory";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == "true" ]];
then
echo contrun $contrun
domcontip=` host $domcont.$doms | awk '{print $NF}'`
ip1=` echo $domcontip | awk -F. '{print $1}'`;
ip2=` echo $domcontip | awk -F. '{print $2}'`;
ip3=` echo $domcontip | awk -F. '{print $3}'`;
ip4=` echo $domcontip | awk -F. '{print $4}'`;
echo Domain1000:$domain > $web;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Domain_change:'$domain;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info data $logdata user $userreq code Domain1003@@@$domain`;
echo Domain1003@$datenow@$timenow@$domain > ${logging}2 
echo $datenow $timenow info Domain1003@@@$domain >> $glog
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
hostn=`hostname | awk -F. '{print $1}'`;
hostname $hostn.$doms;
/usr/bin/sed -e "s/DOMSMALL/${doms}/g" -e "s/DOMIPCONT/$ip1\.$ip2\.$ip3\.$ip4/g" dhclient.conf > /TopStordata/dhclient.conf 
cp /TopStordata/dhclient.conf /etc/dhclient.conf
sed -e "s/CONT/$domcont/g" -e "s/DOMSMALL/$doms/g" -e "s/DOMC/$domc/g" -e "s/DOMSH/$domshort/g" -e "s/DOMIPCONT/$ip1\.$ip2\.$ip3\.$ip4/g" smb4.conf > /TopStordata/smb.conf 
cat CIFSshares.txt >> /TopStordata/smb.conf;
cp /TopStordata/smb.conf /etc/samba/smb.conf;
sed -e "s/DOMC/$domc/g" -e "s/DOMSMALL/$doms/g" -e "s/DOMSH/$domshort/g" -e "s/CONT/$domcont/g" krb5.conf > /TopStordata/krb5.conf;
cp /TopStordata/krb5.conf /etc/ ;
sed -e "s/CONT/$domcont\.$doms/g" -e "s/DOMSMALL/$doms/g" ntp.conf > /TopStordata/ntp.conf ;
systemctl restart smb;
realm join --user=$admin@$domc $domc  2> $txtres ;
if [ $? -ne 0  ]; then
	echo Domain1001:$domain > $web;
	cat $txtres  > ${web}internal;
	logdata='failed_changing_domain:'$domain;
        code='Domain1004@@@'$domain
echo Domain1004@$datenow@$timenow@$domain > ${logging}2 
echo $datenow $timenow error Domain1004@@@$domain >> $glog
else 
 echo Domain1002:$domain > $web; 
 logdata='success_changing_domain:'$domain;
 code='Domain1005@@@'$domain
echo Domain1005@$datenow@$timenow@$domain > ${logging}2 
echo $datenow $timenow info Domain1005@@@$domain >> $glog
fi;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info data $logdata user $userreq code $code`;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
fi
