#!/usr/local/bin/zsh
#cd /root/scripts
cd /TopStor/
logging='/var/www/html/des20/Data/currentinfo2.log';
glog='/TopStordata/TopStor.log';
currentfw=`git branch | grep \* | awk '{print $2}'`
webfile='/usr/local/www/apache24/data/des20/Data';
newfw=`echo $@ | awk '{print $1}'`;
userreq=`echo $@ | awk '{print $2}'`;
privilege="Uploadch";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
 logdata='Start upgrading from version '$currentfw' to version '$newfw;
 logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Upsa1010@@@$currentfw@$newfw`;
 echo Upsa1010@$datenow@$timenow@$currentfw@$newfw > ${logging}2;
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
echo $datenow $timenow info $userreq  Upsa1010@@@$currentfw@$newfw $dtn>> $glog
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;

gitloc='/TopStor';
cd $gitloc  
git add --all;
currentver=`cat ver`;
nfilever=$((filever+0));
ncurrentver=$((currentver+0));
#echo $filever, $ncurrentver;
if [[ $nfilever -ge $ncurrentver ]];
then
#echo ok go;
msg="committing ver"$currentver;
git commit -am "$msg";
git checkout -b ver$filever;
openssl  smime -decrypt  -in $webfile/$filen -binary -inform DEM -inkey key/code2.priv  | gunzip > txt/${filever}.tar  2>&1 
tar -xf txt/${filever}.tar
git add --all
msg="committing ver"$filever;
git commit -am "$msg";
fi 
fi
#rm $webfile/$filen
