#! /usr/local/bin/zsh
cd /TopStor/
traf='/usr/local/www/apache24/data/des19/Data/disklist.txt';
trafdate='/usr/local/www/apache24/data/des19/Data/disklist.txtupdated';
disks=`sysctl kern.disks | awk '{$1=$2=$3=""; print}'`
noofdisks=`echo $disks | wc -w `;
traffic="";
s=0
while (( $s < $noofdisks )) 
do
disknow=` echo $disks | awk '{print $1}'`;
traffic=`echo $traffic disk$s $disknow`;
disks=` echo $disks | awk '{$1=""; print }'`;
s=$(( s+1 ));
done
jsontraffic=`./jsonthis3.sh $traffic`;
echo $jsontraffic > $traf
trafdate=`date +$s`;
jsontrafdate=` ./jsonthis3.sh update $trafdate `
echo $jsontrafdate > $trafdate;
