#!/usr/local/bin/zsh
cd /TopStor
web='/var/www/html/des20/Data/CIFSstatus.log';
logging='/var/www/html/des20/Data/Logs.log'
glog='/TopStordata/TopStor.log';
dater=`echo $@ | awk '{print $1}'`;
page=`echo $@ | awk '{print $2}'`;
liner=`echo $@ | awk '{print $3}'`;
place=`echo $@ | awk '{print $4}'`;
web='/var/www/html/des20/Data/'$pace;
userreq=` echo $@ | awk '{print $4}'`;
privilege='Logs';
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 start=`tac $glog | head -n 1 | awk '{print $1}' ` 
 ifsmall=`cat $glog | head -n 1 | awk '{print $1}' ` 
 iflarge=$start
 if [ $dater = "0" ]; then
   dater=$start
 else
  dater=$((dater/1000))
  start=`echo $start | awk -F'/' '{print $3}'``echo $start | awk -F'/' '{print $1}'``echo $start | awk -F'/' '{print $2}'`
  echo $start
  start=` date +%s -d $start`
  echo $start, $dater
  if [ $((dater)) -gt $((start)) ]; then
   dater=$iflarge;
  else 
   start=$ifsmall
   start=`echo $start | awk -F'/' '{print $3}'``echo $start | awk -F'/' '{print $1}'``echo $start | awk -F'/' '{print $2}'`
   start=` date +%s -d $start`
   if [ $((dater)) -lt $((start)) ]; then
    dater=$ifsmall;
   else
    dater=`date -d '@'$dater +%m/%d/%Y`
   fi
  fi
 fi
 headlines=$((page*liner))
 dater=`echo $dater | sed -e 's/\//\\\\\//g'`
 startline=`tac $glog | awk "/$dater/{ print NR; exit }"`
 if [ $page -eq 1 ]; then
  tojson=$(tac $glog | tail -n +$startline | head -n $headlines)
 else
  tojson=$(tac $glog | tail -n +$startline | head -n $headlines | tail -n $liner)
 fi
 result="[";
 echo ${tojson[@]} | while read -r line;  do
  datenow=`echo $line | awk '{print $1}'`
  timenow=`echo $line | awk '{print $2}'`
  msg=`echo $line | awk '{print $3}'`
  user=`echo $line | awk '{print $4}' `
  code=`echo $line | awk '{print $5}' `
  stamp=`echo $line | awk '{print $6}'`
  subres=`./jsonthis3.sh Date $datenow time $timenow msg $msg user $user code $code stamp $stamp `;
  result=$result$subres,
 done;
 result=`echo $result | rev | cut -c 2- | rev`]
 echo $result;
 echo $result > $logging
 touch ${logging}updated
fi
