#! /usr/local/bin/zsh
cd /TopStor/;
websnaps='/usr/local/www/apache24/data/des19/Data/Vollist.txt';
resweb='/usr/local/www/apache24/data/des19/Data/Vollist.txtupdated';
quota=`/sbin/zfs get -t filesystem -Hp quota | grep Data/  | awk -v CONVFMT=%2.5f '{gsub($3,$3/1048576); print $1" "$3}'`;
logicalused=`/sbin/zfs get -t filesystem -Hp logicalused | grep Data/ | awk -v CONVFMT=%.5g '{gsub($3,$3/1048576); print $1" "$3}'`
avail=`/sbin/zfs get -t filesystem -Hp avail | grep Data/ | awk -v CONVFMT=%.5g '{gsub($3,$3/1048576); print $1" "$3}'`;
used=`/sbin/zfs get -t filesystem -Hp used | grep Data/ | awk -v CONVFMT=%.5g '{gsub($3,$3/1048576); print $1" "$3}'` 
creation=`/sbin/zfs get -t filesystem -H creation | grep Data/  | awk  '{$3=$5"-"$4"-"$7; print $1" "$3}'`;
compressratio=`/sbin/zfs get -t filesystem -Hp compressratio | grep Data/ | awk  '{print $1" "$3}'`;
dedup=`/sbin/zfs get -t filesystem -Hp dedup | grep Data/ | awk '{print $1" "$3}'`;
CIFSshare=`/sbin/zfs get -t filesystem prot:kind  | grep Data/ | grep CIFS  | awk '{print $1" "$3}'`;
NFSshare=`/sbin/zfs get -t filesystem  prot:kind | grep Data/ | grep NFS | awk '{print $1" "$3}'`;
nameof=`/sbin/zfs get -t filesystem -Hp name | grep Data/ | awk -F/ '{print $2}' | awk '{print $1}'`;
result="[";
echo $nameof | while read -r line; do
	q=` echo $quota | grep "$line" | awk '{print $2}'`;
	lo=`echo $logicalused | grep "$line" | awk '{print $2}'`;
	av=`echo $avail | grep "$line" | awk '{print $2}'`;
	us=`echo $used | grep "$line" | awk '{print $2}'`;
	cr=`echo $creation | grep "$line" | awk '{print $2}'`;
	co=`echo $compressratio | grep "$line" | awk '{print $2}'`;
	de=`echo $dedup | grep "$line" | awk '{print $2}'`;
	nf=`echo $NFSshare | grep "$line" | awk '{print $2}'`;
	ci=`echo $CIFSshare | grep "$line" | awk '{print $2}'`;
	subres=`./jsonthis3.sh Pool Data name $line volsize $q volact $lo snaps $av used $us crdate $cr compress $co dedup $de protocol $ci$nf` ;
	result=$result$subres,
done;
result=`echo $result | rev | cut -c 2- | rev`]
echo $result > $websnaps 2>txt/err.txt
tstamp=`date +%s`;
res=` ./jsonthis3.sh updated $tstamp `;
echo $res > $resweb;

