#! /usr/local/bin/zsh
cd /TopStor/;
websnaps='/usr/local/www/apache24/data/des19/Data/listsnaps.txt';
namearray=`/sbin/zfs list -t snapshot -H -o name,creation`; 
result='[';
echo "$namearray" | while read -r line 
do
 onlyname=` echo $line | awk '{print $1}' | awk -F@ '{print $2}'`;
 father=` echo $line | awk '{print $1}' | awk -F@ '{print $1}' | awk -F/ '{print $2}'`;
 name=`echo $line | awk '{print $1}'`;
 creat=` echo $line  | rev | awk  '{print $1" " $2"  " $3" " $4" " $5}' | rev `;
 creatform=`date -f %c $creat +%m/%d/%y`; 
 time=` date -f %c $creat +%X `;
 subres=`zsh jsonthis3.sh name $name onlyname $onlyname father $father creation $creatform time $time; `;
 result=$result$subres,;
 
done
 result=${result%?}]
echo $result
echo $result >$websnaps
