#!/bin/sh

afold='/pace /TopStor /var/www/html/des20/ --exclude /var/www/html/des20/Data';
fold=`echo $@ | awk '{print $1}'`
cd /TopStordata
#find $afold -type f -print0 | xargs -0 sha512sum > ${fold}.sha
git format-patch master --stdout
tar -czvf ${fold}.tar.gz $afold
 openssl  rsautl -encrypt -inkey /TopStor/key/public_key.pem -pubin -in ${fold}.tar.gz -out ${fold}
