#! /usr/local/bin/zsh
web='/usr/local/www/apache24/data/des19/Data/status.log';
rm txt/err; 
hostn=`echo $@ | awk '{ print $1 }' `;
hostip=`echo $@ | awk '{ print $2 }'`;
hostrout=`echo $@ | awk '{ print $3 }'`;
hostdns=` echo $@ | awk '{ print $4 }'`
echo changing box name and ips.... > $web;
echo name_servers=\"$hostdns\" > txt/resolvconf.conf
sed -e "s/HOSTNAME/$hostn/g" -e "s/IPADD/$hostip/g" -e "s/ROUTE/$hostrout/g" rc.conf > txt/rc.conf
cp txt/resolvconf.conf /etc/
cp txt/rc.conf /etc/
hostname $hostn
resolvconf -u
/etc/rc.d/netif restart && /etc/rc.d/routing restart;
route delete default;
route add default $hostrout
echo changes are done.. some moments and will see them > $web
