#!/usr/local/bin/zsh
web='/usr/local/www/apache24/data/des19/Data/'$0'status.log';
logging='/usr/local/www/apache24/data/des19/Data/currentinfo2.log';
rm txt/err; 
hostn=`echo $@ | awk '{ print $1 }' `;
hostip=`echo $@ | awk '{ print $2 }'`;
hostrout=`echo $@ | awk '{ print $3 }'`;
hostdns=` echo $@ | awk '{ print $4 }'`
userreq=` echo $@ | awk '{ print $5 }'`;
privilege="Error";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]];
then
echo HostManual1000: > $web;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='changing_box_to:'$hostn'_'$hostip'_'$hostrout'_'$hostdns;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code HostManual1002@@@.`;
echo HostManual1002@$datenow@$timenow@. > ${logging}2
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging; 
echo name_servers=\"$hostdns\" > txt/resolvconf.conf
sed -e "s/HOSTNAME/$hostn/g" -e "s/IPADD/$hostip/g" -e "s/ROUTE/$hostrout/g" rc.conf > txt/rc.conf
cp txt/resolvconf.conf /etc/
cp txt/rc.conf /etc/
hostname $hostn
resolvconf -u
/etc/rc.d/netif restart && /etc/rc.d/routing restart;
route delete default;
route add default $hostrout
echo HostManual1001: > $web
logdata='success_changing_box_to:'$hostn'_'$hostip'_'$hostrout'_'$hostdns;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code HostManual1003@@@.`;
echo HostManual1003@$datenow@$timenow@. > ${logging}2
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging; 
fi
reboot;

