#!/bin/bash
# GENERATED by the rocky-setup-to-script skill from: /root/ptopstor/DEVELOPMENT.md (+ manage.sh, Dockerfiles, scripts/)
# Target: Rocky Linux 9 — run as root: ./installer.sh   (re-run any time to resume)
PROV_NAME="topstor-host"
# >>> resumable-lib.sh is pasted here by scripts/build_installer.sh <<<
# resumable-lib.sh — embedded at the top of every generated installer.
# Gives: step tracking, resume after reboot/crash, locking, logging.
# Contract: every step body must be IDEMPOTENT (safe to run twice), because a
# step interrupted midway (SSH drop, power loss) is re-run from its start.

PROV_NAME="${PROV_NAME:-provision}"
PROV_SCRIPT="$(readlink -f "${BASH_SOURCE[${#BASH_SOURCE[@]}-1]}")"
PROV_STATE="${PROV_STATE:-/var/lib/$PROV_NAME}"
PROV_LOG="${PROV_LOG:-/var/log/$PROV_NAME.log}"
PROV_UNIT="/etc/systemd/system/$PROV_NAME-resume.service"
# Dry run: `--dry-run` (or PROV_DRYRUN=1) changes nothing. It lists every step in order as DONE/TODO
# against the real ledger (read-only), marks reboot points, and executes only the steps named in
# PROV_DRYRUN_RUN (default "preflight": read-only checks such as disk, network, branch existence),
# reporting PASS/FAIL without recording anything. No root, no lock, no log, no unit file.
for _a in "$@"; do [ "$_a" = --dry-run ] && PROV_DRYRUN=1; done
PROV_DRYRUN_RUN="${PROV_DRYRUN_RUN:-preflight}"
if [ -n "${PROV_DRYRUN:-}" ]; then
  PROV_REAL_STATE="$PROV_STATE"; PROV_STATE="$(mktemp -d)"; PROV_LOG=/dev/null
  trap 'rm -rf "$PROV_STATE"' EXIT
fi
mkdir -p "$PROV_STATE/done" "$PROV_STATE/failed"

log() { echo "[$(date '+%F %T')] $*" | tee -a "$PROV_LOG"; }

[ -n "${PROV_DRYRUN:-}" ] || [ "$(id -u)" = 0 ] || { echo "run as root" >&2; exit 1; }

# One instance at a time (resume service + a hand-started run must not race).
exec 9>"$PROV_STATE/lock"
[ -n "${PROV_DRYRUN:-}" ] || flock -n 9 || { echo "another $PROV_NAME run is active" >&2; exit 1; }

# Keep a stable copy so the resume unit survives the script's directory vanishing.
if [ -z "${PROV_DRYRUN:-}" ] && [ "$PROV_SCRIPT" != "$PROV_STATE/installer.sh" ]; then
  install -m 0700 "$PROV_SCRIPT" "$PROV_STATE/installer.sh"
fi

# step <id> <description> <function-or-command...>
# Skips if done. On failure records it and aborts so a re-run retries from here.
step() {
  local id="$1" desc="$2"; shift 2
  if [ -n "${PROV_DRYRUN:-}" ]; then
    local st=TODO; [ -e "$PROV_REAL_STATE/done/$id" ] && st=DONE
    printf 'DRYRUN [%s] %s — %s\n' "$st" "$id" "$desc"
    case " $PROV_DRYRUN_RUN " in *" $id "*)
      if ( set -euo pipefail; "$@" ) >/dev/null 2>"$PROV_STATE/err"; then echo "         check $id: PASS"
      else echo "         check $id: FAIL — $(tail -3 "$PROV_STATE/err" | tr '\n' ' ')"; PROV_DRYRUN_FAILED=1; fi;;
    esac
    return 0
  fi
  if [ -e "$PROV_STATE/done/$id" ]; then log "SKIP  $id (already done)"; return 0; fi
  log "START $id — $desc"
  # Not inside `if`/`||`: bash disables errexit in those contexts, which would let a
  # failing command mid-step go unnoticed.
  ( set -euo pipefail; "$@" ) >>"$PROV_LOG" 2>&1
  local rc=$?
  if [ $rc -eq 0 ]; then
    date -Is > "$PROV_STATE/done/$id"; rm -f "$PROV_STATE/failed/$id"
    log "DONE  $id"
  else
    echo "$rc" > "$PROV_STATE/failed/$id"
    log "FAIL  $id (rc=$rc) — fix the cause, then re-run the installer; it resumes here. See $PROV_LOG"
    exit "$rc"
  fi
}

# Ordering helper for steps that must reboot: marks the CURRENT step done
# (call it as the last line of the step body via `request_reboot`), the main
# flow then calls `reboot_if_requested` right after the step returns.
request_reboot() { echo "${1:-reboot requested}" > "$PROV_STATE/reboot-requested"; }

reboot_if_requested() {
  [ -z "${PROV_DRYRUN:-}" ] || { echo "         ^ possible reboot point (only if the step above asks for one)"; return 0; }
  [ -e "$PROV_STATE/reboot-requested" ] || return 0
  log "REBOOT: $(cat "$PROV_STATE/reboot-requested")"
  rm -f "$PROV_STATE/reboot-requested"
  cat > "$PROV_UNIT" <<UNIT
[Unit]
Description=Resume $PROV_NAME installer after reboot
After=network-online.target
Wants=network-online.target
ConditionPathExists=$PROV_STATE/installer.sh

[Service]
Type=oneshot
ExecStart=$PROV_STATE/installer.sh
RemainAfterExit=no
TimeoutStartSec=infinity

[Install]
WantedBy=multi-user.target
UNIT
  systemctl daemon-reload
  systemctl enable "$PROV_NAME-resume.service" >/dev/null 2>&1
  sync; sleep 2
  systemctl reboot
  sleep 600; exit 0   # never fall through while the reboot is in flight
}

# Reboot only if the OS says it is needed (kernel/glibc/systemd updated).
reboot_if_os_needs() {
  command -v needs-restarting >/dev/null || dnf -y install dnf-utils >/dev/null 2>&1
  needs-restarting -r >/dev/null 2>&1 || request_reboot "OS updates need a reboot"
}

# put_file <path> <mode> <owner> — content on stdin; rewrites only when different.
put_file() {
  local p="$1" m="${2:-0644}" o="${3:-root:root}" t; t="$(mktemp)"; cat > "$t"
  mkdir -p "$(dirname "$p")"
  cmp -s "$t" "$p" || install -m "$m" -o "${o%%:*}" -g "${o##*:}" "$t" "$p"
  rm -f "$t"
}

# ensure_line <file> <line> — append if absent.
ensure_line() { grep -qxF -- "$2" "$1" 2>/dev/null || echo "$2" >> "$1"; }

# git_sync <url> <dir> <branch> — clone or hard-sync to the branch.
git_sync() {
  if [ -d "$2/.git" ]; then git -C "$2" fetch -q origin && git -C "$2" checkout -q "$3" && git -C "$2" reset -q --hard "origin/$3"
  else git clone -q -b "$3" "$1" "$2"; fi
}

# finish — remove the resume unit; call as the very last thing.
prov_finish() {
  [ -z "${PROV_DRYRUN:-}" ] || { echo "DRYRUN complete (nothing was changed)${PROV_DRYRUN_FAILED:+ — but a check FAILED, fix it before a real run}"; exit "${PROV_DRYRUN_FAILED:-0}"; }
  systemctl disable "$PROV_NAME-resume.service" >/dev/null 2>&1 || true
  rm -f "$PROV_UNIT"; systemctl daemon-reload
  date -Is > "$PROV_STATE/COMPLETE"; log "ALL STEPS COMPLETE"
}

# Flags: --status | --reset-step <id> | --from-scratch
case "${1:-}" in
  --status) ls -1 "$PROV_STATE/done" "$PROV_STATE/failed" 2>/dev/null; exit 0;;
  --reset-step) rm -f "$PROV_STATE/done/$2"; exit 0;;
  --from-scratch) rm -rf "$PROV_STATE/done" "$PROV_STATE/failed" "$PROV_STATE/COMPLETE"; mkdir -p "$PROV_STATE/done" "$PROV_STATE/failed";;
esac


# ---- Variables (secrets come from the environment or /root/.topstor-host.env, never inline) ----
[ -f "/root/.$PROV_NAME.env" ] && . "/root/.$PROV_NAME.env"

# ---- Steps (ordered by dependency; see references/ordering.md) ----
# ============================================================================
# TopStor dev-cluster HOST installer (container flavour) — source: /root/ptopstor/DEVELOPMENT.md
# (§2 images, §3 packages/dirs, §9, §20 redeploy, §20.12 ZFS modules, §21.1-21.13 host + manage.sh).
# manage.sh is used UNCHANGED from the parent repo (REPO_ROOT=/root/topstor is hard-coded in it).
# ============================================================================

# ---- Settings (override in /root/.<name>.env or the environment) -----------
REPO_ROOT="${REPO_ROOT:-/root/topstor}"                       # must stay /root/topstor: manage.sh hard-codes it
PARENT_URL="${PARENT_URL:-https://github.com/MoatazNegm/topstor-cluster.git}"
PARENT_BRANCH="${PARENT_BRANCH:-main}"
APP_BASE_URL="${APP_BASE_URL:-https://github.com/MoatazNegm}" # TopStordev / HC / TopStorWeb live here (§21.8)
APP_BRANCH="${APP_BRANCH:-QSD5.220}"                          # branch checked out in the app repos; confirm with the maintainer (§0)
GITHUB_TOKEN="${GITHUB_TOKEN:-}"                              # only if the repos are private
DOCKERHUB_USER="${DOCKERHUB_USER:-}"; DOCKERHUB_TOKEN="${DOCKERHUB_TOKEN:-}"  # only if pulls need login
HOME_BASE="${HOME_BASE:-/home/topstor}"                       # everything big goes under /home (root disk is small, §21.1)
ZFS_VERSION="${ZFS_VERSION:-2.4.4}"                           # OpenZFS built from source (§20.12)
WITH_ZFS2="${WITH_ZFS2:-yes}"                                 # manage.sh start also starts zfs2 (§21.13)
RUN_DOCKER_SETUP="${RUN_DOCKER_SETUP:-yes}"                   # run /TopStor/docker_setup.sh in zfs1 once and verify (§21.3/21.4)
RUN_MANAGER_SH="${RUN_MANAGER_SH:-no}"                        # manager.sh = wetty/ngrok/filebrowser/nginx side services with host-specific IPs and a token
MIN_FREE_GB="${MIN_FREE_GB:-120}"
SELINUX_REBOOT="${SELINUX_REBOOT:-lazy}"                      # lazy: "disabled" is written to the config and SELinux goes permissive now; the real disable happens at the first reboot that is needed anyway (new kernel). now: force a reboot for it.
SELINUX_MODE="${SELINUX_MODE:-disabled}"                      # disabled | permissive | enforcing. The doc (§21.11) has permissive; disabled needs one reboot to take effect
OPEN_PORTS="${OPEN_PORTS:-2222/tcp 2223/tcp 2224/tcp 5022/tcp 5080/tcp 9418/tcp 8080/tcp 8443/tcp 8444/tcp}"  # ports manage.sh publishes: ssh zfs1/proxy/zfs2/abdopuppet, abdopuppet http+git, proxy http, UI zfs1/zfs2
FIREWALL_MODE="${FIREWALL_MODE:-open-ports}"                  # open-ports | off (stop+disable firewalld) | skip

# Image source: pull from registries (default) or copy from a running reference host over ssh/scp
# (images can be tens of GB). IMAGE_SOURCE_HOST="root@192.168.8.62" switches to host mode;
# the key-based ssh login (ssh-copy-id) must already work, no password prompts are possible here.
IMAGE_SOURCE_HOST="${IMAGE_SOURCE_HOST:-}"
IMAGE_SOURCE="${IMAGE_SOURCE:-$([ -n "$IMAGE_SOURCE_HOST" ] && echo auto || echo registry)}"  # registry | host | auto (host first, registry fallback)
IMAGE_SOURCE_SSH_PORT="${IMAGE_SOURCE_SSH_PORT:-22}"
COPY_NESTED_GRAPH="${COPY_NESTED_GRAPH:-no}"                  # host mode: also rsync the ready nested-dockerd graph roots (≈25 GB each) instead of letting docker-preload.sh fill them
# Extra things to copy from the source host (VM disks, libvirt XML, ...): "srcpath:destpath" entries, space separated
EXTRA_RSYNC_PATHS="${EXTRA_RSYNC_PATHS:-}"
QUICKSTOR_UI_TAR="${QUICKSTOR_UI_TAR:-}"                      # quickstor-ui:latest is a local build, not on a registry: path to its tarball if you have one

HOST_IMAGES=(                                                 # name that manage.sh uses  <-  registry source
  "moataznegm/topstor-zfs:current|moataznegm/topstor-zfs:current"
  "topstor/proxy:fixed|moataznegm/topstor-proxy:cluster-fixed"
  "topstor/abdopuppet:latest|moataznegm/topstor-abdopuppet:cluster-latest"
)
NESTED_IMAGES=(                                               # pulled to the host, saved as tarballs for zfs1/zfs2 docker-preload (§2, §21.2)
  moataznegm/quickstor:git moataznegm/quickstor:dns moataznegm/quickstor:etcd
  moataznegm/quickstor:etcdclient moataznegm/quickstor:smb moataznegm/quickstor:flask3
  moataznegm/aiwork:wetty-patched
  prom/node-exporter:latest gcr.io/cadvisor/cadvisor:latest prom/prometheus:latest grafana/grafana:latest
)
NESTED_CURRENT_IMAGES=(                                       # present in the live nested graph; all exist on Docker Hub
  moataznegm/grafana:current moataznegm/prometheus:current moataznegm/node-exporter:current
  moataznegm/cadvisor:current moataznegm/alpine:current moataznegm/abdopuppet:current
)
APP_REPOS=("TopStordev:TopStor" "HC:pace" "TopStorWeb:topstorweb")   # GitHub name : directory under volumes/linux-env
LOOP_NODES=(1 2 3 7)                                          # /dev/loop1-3 (10 GB) and loop7 (2 GB cache disk), manage.sh attaches them

DISK_DIR="$HOME_BASE/disks"; IMG_DIR="$HOME_BASE/zfs-docker-images"
SRC_SSH=(ssh -p "$IMAGE_SOURCE_SSH_PORT" -o BatchMode=yes -o ConnectTimeout=15 -o StrictHostKeyChecking=accept-new)

retry() { local n=$1; shift; local i; for i in $(seq 1 "$n"); do "$@" && return 0; echo "retry $i/$n: $*"; sleep $((i*10)); done; return 1; }
img_present() { docker image inspect "$1" >/dev/null 2>&1; }
tar_name() { echo "$IMG_DIR/$(echo "$1" | tr '/:' '__').tar"; }
use_host_source() { [ "$IMAGE_SOURCE" != registry ] && [ -n "$IMAGE_SOURCE_HOST" ]; }
registry_ok() { [ "$IMAGE_SOURCE" != host ]; }

# ---- 1. Preflight ----------------------------------------------------------
preflight() {
  . /etc/os-release; [ "${ID%%-*}" = rocky ] || [ "$ID" = rhel ] || { echo "expected Rocky/RHEL, got $ID"; exit 1; }
  [ "${VERSION_ID%%.*}" = 9 ] || { echo "expected major version 9, got $VERSION_ID"; exit 1; }
  [ "$REPO_ROOT" = /root/topstor ] || { echo "REPO_ROOT must be /root/topstor (manage.sh hard-codes it)"; exit 1; }
  mkdir -p /home; local free; free=$(df -BG --output=avail /home | tail -1 | tr -dc 0-9)
  [ "$free" -ge "$MIN_FREE_GB" ] || { echo "only ${free} GB free under /home, need $MIN_FREE_GB (images and nested docker data live there)"; exit 1; }
  while pgrep -x dnf >/dev/null; do echo "waiting for another dnf"; sleep 5; done
  curl -fsI https://github.com >/dev/null || { echo "github.com unreachable"; exit 1; }
  if registry_ok; then curl -fsI https://registry-1.docker.io/v2/ >/dev/null 2>&1 || [ $? -eq 22 ] || { echo "Docker Hub unreachable"; exit 1; }; fi
  if use_host_source; then
    "${SRC_SSH[@]}" "$IMAGE_SOURCE_HOST" 'docker info >/dev/null && echo source-ok' | grep -q source-ok \
      || { echo "cannot ssh to $IMAGE_SOURCE_HOST with a key and run docker there (run ssh-copy-id first, or set IMAGE_SOURCE=registry)"; exit 1; }
  fi
  local r; for r in "${APP_REPOS[@]}"; do
    [ -n "$(git ls-remote --heads "$APP_BASE_URL/${r%%:*}.git" "$APP_BRANCH" 2>/dev/null)" ] \
      || { echo "branch $APP_BRANCH not found in $APP_BASE_URL/${r%%:*}.git — set APP_BRANCH (the maintainer decides it, §0) or GITHUB_TOKEN"; exit 1; }
  done
}
step preflight "OS, disk, network, branch checks" preflight

# ---- 2. Repos, update, reboot point A --------------------------------------
repos() { dnf -y install epel-release dnf-plugins-core; dnf config-manager --set-enabled crb
  dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo; }
step repos "EPEL, CRB, Docker CE repo" repos

selinux_mode() {
  sed -i "s/^SELINUX=.*/SELINUX=$SELINUX_MODE/" /etc/selinux/config
  case "$SELINUX_MODE" in
    enforcing)  setenforce 1 || true;;
    *)          setenforce 0 || true                                  # permissive now; "disabled" only takes effect after a reboot
                [ "$SELINUX_MODE" = disabled ] && [ "$SELINUX_REBOOT" = now ] && [ "$(getenforce)" != Disabled ] && request_reboot "SELinux disabled needs a reboot";;
  esac
  true
}
step selinux "SELinux -> $SELINUX_MODE (config now; permissive live; no extra reboot unless SELINUX_REBOOT=now)" selinux_mode

os_update() { dnf -y update; reboot_if_os_needs; }
step os-update "dnf update (reboots first if the kernel changed, so ZFS is built for the final kernel)" os_update
reboot_if_requested   # one reboot covers SELinux-disable and a new kernel

# ---- 3. Packages (§21.11, §20.12) ------------------------------------------
pkg_host() {
  dnf -y install git curl wget tar xz gzip rsync jq which procps-ng util-linux iproute iproute-tc net-tools \
    chrony NetworkManager firewalld policycoreutils nmap-ncat openssh-clients \
    targetcli python3 python3-pip python3-rtslib iscsi-initiator-utils \
    gcc gcc-c++ make rpm-build openssl-devel elfutils-libelf-devel libtirpc-devel libuuid-devel libblkid-devel zlib-devel \
    kernel-headers
}
step pkg-host "host packages (storage tools, build chain, chrony, NetworkManager, firewalld)" pkg_host

docker_engine() {
  dnf -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  # §0/§21.1: never restart a running dockerd; only start it when it is not up.
  /usr/bin/systemctl is-active --quiet docker || /usr/bin/systemctl enable --now docker
  /usr/bin/systemctl enable docker containerd >/dev/null 2>&1
  if [ -n "$DOCKERHUB_USER" ]; then echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USER" --password-stdin; fi
}
step docker-engine "Docker CE (started only if not already running)" docker_engine

# ---- 4. Host OS settings ---------------------------------------------------
host_services() {
  /usr/bin/systemctl enable --now chronyd firewalld NetworkManager
  # §21.11: iscsid and target must stay OFF on the host (zfs1 runs its own iscsid in the host netns)
  /usr/bin/systemctl disable --now iscsid.service iscsid.socket target.service 2>/dev/null || true
  /usr/bin/systemctl enable rc-local.service 2>/dev/null || true
  [ -f /usr/local/bin/systemctl ] && echo "WARN: /usr/local/bin/systemctl shadows /usr/bin/systemctl (§21.11); scripts here use /usr/bin/systemctl"
  true
}
step host-services "enable chronyd/firewalld/NM, keep iscsid+target off" host_services

firewall_ports() {
  case "$FIREWALL_MODE" in
    skip) return 0;;
    off)  /usr/bin/systemctl disable --now firewalld; return 0;;
  esac
  /usr/bin/systemctl is-active --quiet firewalld || /usr/bin/systemctl enable --now firewalld
  # Runtime AND permanent, no --reload: a reload makes firewalld rebuild its rules and can drop Docker's
  # chains, and dockerd must not be restarted (§21.1).
  local p; for p in $OPEN_PORTS; do
    firewall-cmd --add-port="$p" >/dev/null; firewall-cmd --permanent --add-port="$p" >/dev/null
  done
  firewall-cmd --list-ports
}
step firewall "open the ports manage.sh publishes (no eno1/route/INPUT-rule changes, no reload)" firewall_ports

kernel_modules() {
  put_file /etc/modules-load.d/topstor.conf <<'C'
# Modules the privileged zfs containers use (DEVELOPMENT.md §21.11); spl/zfs are in zfs.conf
loop
bonding
veth
overlay
nf_conntrack
target_core_mod
target_core_iblock
iscsi_target_mod
tcm_loop
iscsi_tcp
C
  local m; while read -r m; do case "$m" in \#*|"") ;; *) modprobe "$m" || echo "WARN: modprobe $m failed";; esac; done < /etc/modules-load.d/topstor.conf
  put_file /etc/sysctl.d/90-topstor.conf <<'C'
net.ipv4.ip_forward = 1
C
  sysctl --system >/dev/null
}
step kernel-modules "modules-load.d + ip_forward" kernel_modules

# ZFS kernel modules: rebuilt per running kernel (§20.12). The step id carries the kernel version so a new
# kernel simply makes this step run again.
zfs_module() {
  if modinfo -k "$(uname -r)" zfs >/dev/null 2>&1 && modprobe zfs 2>/dev/null; then echo "zfs already built for $(uname -r)"; return 0; fi
  dnf -y install "kernel-devel-$(uname -r)" || dnf -y install kernel-devel
  [ -d "/usr/src/kernels/$(uname -r)" ] || { echo "kernel-devel for $(uname -r) not available; update+reboot first"; return 1; }
  dnf -y reinstall "kernel-devel-$(uname -r)" || true            # §20.12 step 3: pristine kernel-devel
  local b="$HOME_BASE/build"; mkdir -p "$b"; cd "$b"
  [ -d "zfs-$ZFS_VERSION" ] || { retry 3 wget -q "https://github.com/openzfs/zfs/releases/download/zfs-$ZFS_VERSION/zfs-$ZFS_VERSION.tar.gz"; tar -xzf "zfs-$ZFS_VERSION.tar.gz"; }
  cd "zfs-$ZFS_VERSION"
  ./configure --with-linux="/usr/src/kernels/$(uname -r)" --with-linux-obj="/usr/src/kernels/$(uname -r)"
  make -C module -j"$(nproc)"
  mkdir -p "/lib/modules/$(uname -r)/extra"
  cp module/spl.ko module/zfs.ko "/lib/modules/$(uname -r)/extra/"
  depmod -a; modprobe zfs
  lsmod | grep -qE '^zfs '
}
step "zfs-module-$(uname -r)" "build + load OpenZFS $ZFS_VERSION modules for the running kernel" zfs_module

zfs_autoload() { put_file /etc/modules-load.d/zfs.conf <<'C'
# Auto-load ZFS kernel modules on boot
# Required so the zfs container can use /dev/zfs after host restart.
spl
zfs
C
}
step zfs-autoload "ZFS modules load at boot" zfs_autoload

# ---- 5. Parent repo (manage.sh etc. — used unchanged) ----------------------
git_creds() {
  [ -n "$GITHUB_TOKEN" ] || return 0
  git config --global credential.helper store
  grep -qF "github.com" /root/.git-credentials 2>/dev/null || { umask 077; echo "https://x-access-token:${GITHUB_TOKEN}@github.com" >> /root/.git-credentials; }
}
step git-creds "GitHub credential (only when GITHUB_TOKEN is set)" git_creds

parent_repo() {
  if [ -d "$REPO_ROOT/.git" ]; then git -C "$REPO_ROOT" fetch -q origin || true; echo "parent repo exists, left as is"; return 0; fi
  [ ! -e "$REPO_ROOT" ] || [ -z "$(ls -A "$REPO_ROOT")" ] || { echo "$REPO_ROOT exists and is not a git checkout"; return 1; }
  retry 3 git clone -q -b "$PARENT_BRANCH" "$PARENT_URL" "$REPO_ROOT"
  test -x "$REPO_ROOT/manage.sh" -o -f "$REPO_ROOT/manage.sh"
  test -f "$REPO_ROOT/scripts/entrypoint-zfs.sh"
}
step parent-repo "clone topstor-cluster into /root/topstor (manage.sh, scripts, Dockerfiles)" parent_repo

app_repos() {
  local le="$REPO_ROOT/volumes/linux-env" r gh dir
  mkdir -p "$le"
  for r in "${APP_REPOS[@]}"; do gh=${r%%:*}; dir=$le/${r##*:}
    if [ -d "$dir/.git" ]; then git -C "$dir" fetch -q origin; git -C "$dir" checkout -q "$APP_BRANCH" 2>/dev/null || git -C "$dir" checkout -q -b "$APP_BRANCH" "origin/$APP_BRANCH"
    else rmdir "$dir" 2>/dev/null || true; retry 3 git clone -q -b "$APP_BRANCH" "$APP_BASE_URL/$gh.git" "$dir"; fi
  done
}
step app-repos "clone TopStordev/HC/TopStorWeb into volumes/linux-env at $APP_BRANCH" app_repos

# ---- 6. Directories, seeds, side workspaces (§3, §21.2, §20.5, §21.8, §21.13) ----
workspace_dirs() {
  local v="$REPO_ROOT/volumes"
  mkdir -p "$v/linux-env/root" "$v/linux-env/TopStordata" "$v/linux-env/etc-networkmanager-conf.d" "$v/zfs-tmp" "$v/puppet-srv" "$v/linux-env-proxy" \
           "$HOME_BASE/zfs-docker-data" "$IMG_DIR" "$DISK_DIR"
  [ -f "$v/zfs-tmp/docker_setup_disabled" ] || : > "$v/zfs-tmp/docker_setup_disabled"       # dev-mode flag: docker_setup.sh does not auto-run at boot
  [ -f "$v/linux-env/etc-networkmanager-conf.d/hostname-mode.conf" ] || put_file "$v/linux-env/etc-networkmanager-conf.d/hostname-mode.conf" <<'C'
[main]
hostname-mode=none
C
  chmod 700 "$IMG_DIR"
}
step workspace-dirs "volumes/, /home/topstor/{disks,zfs-docker-data,zfs-docker-images}, dev-mode flag, NM hostname-mode" workspace_dirs

puppet_srv() {
  local le="$REPO_ROOT/volumes/linux-env" ps="$REPO_ROOT/volumes/puppet-srv" r gh dir
  for r in "${APP_REPOS[@]}"; do gh=${r%%:*}; dir=$le/${r##*:}
    if [ -d "$ps/$gh.git" ]; then git -C "$ps/$gh.git" fetch -q "$dir" '+refs/heads/*:refs/heads/*'
    else git clone -q --bare "$dir" "$ps/$gh.git"; fi
  done
}
step puppet-srv "bare repos served by abdopuppet (git://10.11.11.252)" puppet_srv

proxy_workspace() {
  local pw="$REPO_ROOT/volumes/linux-env-proxy" r gh dir
  mkdir -p "$pw"
  for r in "${APP_REPOS[@]}"; do gh=${r%%:*}; dir=$pw/${r##*:}
    [ -d "$dir/.git" ] && continue
    retry 3 git clone -q -b "$APP_BRANCH" "$APP_BASE_URL/$gh.git" "$dir"
    git -C "$dir" remote rename origin github
    git -C "$dir" remote add origin "git://10.11.11.252/$gh.git"       # §21.8
  done
}
step proxy-workspace "proxy container workspace (origin=252, github=GitHub)" proxy_workspace

zfs2_tree() {
  [ "$WITH_ZFS2" = yes ] || return 0
  local z="$HOME_BASE/zfs2" le="$REPO_ROOT/volumes/linux-env" d
  mkdir -p "$z/linux-env/root" "$z/linux-env/TopStordata" "$z/tmp" "$HOME_BASE/zfs2-docker-data"
  : > "$z/tmp/docker_setup_disabled"
  rsync -a "$le/etc-networkmanager-conf.d/" "$z/linux-env/etc-networkmanager-conf.d/"
  for d in TopStor pace topstorweb; do [ -d "$z/linux-env/$d/.git" ] || rsync -a "$le/$d/" "$z/linux-env/$d/"; done
}
step zfs2-tree "zfs2 workspace copies under /home/topstor/zfs2 (§21.13)" zfs2_tree

# ---- 7. Images: ALL of them pulled/copied, nothing is built ----------------
login_registry() { :; }

# one image: host mode first (ssh docker save | docker load), then registry
fetch_image() {   # <local-name> <registry-name>
  local local_name=$1 reg=$2
  img_present "$local_name" && { echo "have $local_name"; return 0; }
  if use_host_source; then
    if "${SRC_SSH[@]}" "$IMAGE_SOURCE_HOST" "docker image inspect '$local_name' >/dev/null 2>&1"; then
      echo "copying $local_name from $IMAGE_SOURCE_HOST"
      "${SRC_SSH[@]}" "$IMAGE_SOURCE_HOST" "docker save '$local_name'" | docker load && return 0
    fi
    [ "$IMAGE_SOURCE" = host ] && { echo "$local_name not on $IMAGE_SOURCE_HOST"; return 1; }
  fi
  retry 4 docker pull "$reg"
  [ "$reg" = "$local_name" ] || docker tag "$reg" "$local_name"
}

images_host() {
  local e; for e in "${HOST_IMAGES[@]}"; do fetch_image "${e%%|*}" "${e##*|}"; done
  docker tag topstor/proxy:fixed moataznegm/topstor-proxy:current 2>/dev/null || true
}
step images-host "images run by manage.sh: zfs, proxy, abdopuppet" images_host

images_nested() {
  local i t; mkdir -p "$IMG_DIR"
  for i in "${NESTED_IMAGES[@]}" "${NESTED_CURRENT_IMAGES[@]}"; do fetch_image "$i" "$i"; done
  # tarballs for docker-preload.sh (loaded by the nested dockerd of every zfs node)
  if use_host_source; then
    rsync -a --partial -e "ssh -p $IMAGE_SOURCE_SSH_PORT -o BatchMode=yes" "$IMAGE_SOURCE_HOST:$IMG_DIR/" "$IMG_DIR/" || echo "WARN: rsync of $IMG_DIR from source failed, saving from local images"
  fi
  for i in "${NESTED_IMAGES[@]}"; do t=$(tar_name "$i")
    [ -s "$t" ] || [ -s "${t%.tar}.tar" ] || { docker save "$i" -o "$t.part" && mv "$t.part" "$t"; }
  done
  t="$IMG_DIR/moataznegm_current-images.tar"
  [ -s "$t" ] || { docker save "${NESTED_CURRENT_IMAGES[@]}" -o "$t.part" && mv "$t.part" "$t"; }
  chmod 600 "$IMG_DIR"/*.tar
}
step images-nested "nested images (quickstor, prometheus, grafana, wetty, cadvisor, node-exporter) + tarballs for docker-preload" images_nested

images_ui() {
  if [ -n "$QUICKSTOR_UI_TAR" ]; then
    [ -f "$QUICKSTOR_UI_TAR" ] || { echo "QUICKSTOR_UI_TAR not found: $QUICKSTOR_UI_TAR"; return 1; }
    docker load -i "$QUICKSTOR_UI_TAR"; cp -n "$QUICKSTOR_UI_TAR" "$IMG_DIR/quickstor-ui_latest.tar"; return 0
  fi
  if use_host_source && "${SRC_SSH[@]}" "$IMAGE_SOURCE_HOST" "docker image inspect quickstor-ui:latest >/dev/null 2>&1"; then
    fetch_image quickstor-ui:latest quickstor-ui:latest
    [ -s "$IMG_DIR/quickstor-ui_latest.tar" ] || docker save quickstor-ui:latest -o "$IMG_DIR/quickstor-ui_latest.tar"
    return 0
  fi
  echo "WARN: quickstor-ui:latest is a local build, not on a registry. Set QUICKSTOR_UI_TAR or IMAGE_SOURCE_HOST to provide it."
}
step images-ui "quickstor-ui:latest (local build; copied from the source host or a tarball when available)" images_ui

source_extras() {
  use_host_source || return 0
  local e s d
  if [ "$COPY_NESTED_GRAPH" = yes ]; then
    for e in "$HOME_BASE/zfs-docker-data" "$HOME_BASE/zfs2-docker-data"; do mkdir -p "$e"
      rsync -aH --partial --info=progress0 -e "ssh -p $IMAGE_SOURCE_SSH_PORT -o BatchMode=yes" "$IMAGE_SOURCE_HOST:$e/" "$e/"; done
  fi
  for e in $EXTRA_RSYNC_PATHS; do s=${e%%:*}; d=${e##*:}; mkdir -p "$d"
    rsync -aH --partial -e "ssh -p $IMAGE_SOURCE_SSH_PORT -o BatchMode=yes" "$IMAGE_SOURCE_HOST:$s/" "$d/"; done
}
step source-extras "optional: nested graph roots and extra VM/disk paths from the source host (rsync, resumable)" source_extras

# ---- 8. Boot hook, devices, cluster start -----------------------------------
rc_local() {
  put_file /etc/rc.d/rc.local 0755 <<C
#!/bin/bash
# Written by the TopStor host installer (DEVELOPMENT.md §21.11): the repo copy of manage.sh is the single source of truth.
touch /var/lock/subsys/local
sh /root/topstor/manage.sh
$( [ "$RUN_MANAGER_SH" = yes ] && echo 'sh /root/topstor/manager.sh' || echo '# sh /root/topstor/manager.sh   (side services; enable with RUN_MANAGER_SH=yes)' )
C
  chmod +x /etc/rc.d/rc.local; /usr/bin/systemctl enable rc-local.service 2>/dev/null || true
}
step rc-local "/etc/rc.d/rc.local runs manage.sh at boot" rc_local

loop_nodes() {
  local n; for n in "${LOOP_NODES[@]}"; do [ -b "/dev/loop$n" ] || mknod "/dev/loop$n" b 7 "$n"; done
}
step loop-nodes "make sure /dev/loop{1,2,3,7} exist (manage.sh ensure_loop_disks attaches the 10 GB / 2 GB files)" loop_nodes

cluster_start() {
  cd "$REPO_ROOT"
  # manage.sh (unchanged): network topstor_gitnet, loop disks, abdopuppet, zfs1, zfs2, proxy, chrony link
  sh "$REPO_ROOT/manage.sh" start
  local i; for i in $(seq 1 30); do docker ps --format '{{.Names}}' | grep -qx zfs1 && break; sleep 2; done
  sh "$REPO_ROOT/manage.sh" status | tee /dev/stderr | grep -q DOWN && return 1 || true
}
step cluster-start "manage.sh start: abdopuppet, zfs1, zfs2, proxy" cluster_start

# ---- 9. docker_setup.sh in zfs1 (dev loop §21.3), then acceptance (§21.4) --
zfs1_ready() {
  # nested dockerd up and docker-preload finished loading the tarballs
  local want=$(( ${#NESTED_IMAGES[@]} )) i n
  for i in $(seq 1 180); do
    n=$(docker exec zfs1 docker images -q 2>/dev/null | wc -l)
    [ "${n:-0}" -ge "$want" ] && return 0; sleep 10
  done
  echo "nested images not loaded in zfs1 (have ${n:-0}, want >= $want); check: docker logs zfs1"; return 1
}
step zfs1-ready "wait for nested dockerd + docker-preload in zfs1" zfs1_ready

docker_setup_run() {
  [ "$RUN_DOCKER_SETUP" = yes ] || { echo "RUN_DOCKER_SETUP=$RUN_DOCKER_SETUP — skipped"; return 0; }
  docker exec zfs1 test -x /TopStor/docker_setup.sh -o -f /TopStor/docker_setup.sh
  # No TTY (docker exec -t would kill the background loopers). fd 9 (installer lock) is closed for the detached child.
  setsid nohup docker exec zfs1 bash /TopStor/docker_setup.sh > /var/log/topstor-docker_setup.log 2>&1 9>&- < /dev/null &
  sleep 5; echo "docker_setup.sh started in zfs1; log: /var/log/topstor-docker_setup.log"
}
step docker-setup-run "start /TopStor/docker_setup.sh in zfs1 (detached, no TTY)" docker_setup_run

verify_cluster() {
  [ "$RUN_DOCKER_SETUP" = yes ] || return 0
  local i ok=0
  # docker_setup.sh takes minutes; acceptance asks for stability of >= 6 minutes (§21.4)
  for i in $(seq 1 90); do
    if docker exec zfs1 nmcli -t conn show 2>/dev/null | grep -q '^cmynode:' \
       && docker exec zfs1 nmcli -t conn show 2>/dev/null | grep -q '^slave-eth10-to-bond0:' \
       && ! docker exec zfs1 ip -4 -o addr show dev eth10 2>/dev/null | grep -q inet; then ok=1; break; fi
    sleep 10
  done
  [ $ok = 1 ] || { echo "nmcli acceptance failed: expected cmynode->bond0, slave-eth10-to-bond0->eth10, eth10 without IP"; return 1; }
  sleep 360
  docker exec zfs1 nmcli -t conn show | grep -q '^slave-eth10-to-bond0:' || { echo "slave profile vanished within 6 min"; return 1; }
  docker exec zfs1 nmcli -t dev status | grep -E '^(bond0|eth10):' | grep -qv ':connected' && { echo "device not connected"; return 1; } || true
  curl -ksf -o /dev/null https://10.11.11.250/ || { echo "React UI https://10.11.11.250/ not 200"; return 1; }
  curl -sf -o /dev/null http://10.11.11.250:5001/ || { echo "flask :5001 not 200"; return 1; }
  curl -sf http://10.11.11.250:9090/-/ready >/dev/null || { echo "prometheus not ready"; return 1; }
  curl -ksf -o /dev/null https://10.11.11.250:4000/login || { echo "grafana not 200"; return 1; }
  docker exec zfs1 pgrep -f fapilooper.sh >/dev/null || { echo "fapilooper.sh not running"; return 1; }
}
step verify-cluster "acceptance: nmcli profiles, 6 min stability, UI/flask/prometheus/grafana" verify_cluster


prov_finish
