#! /usr/local/bin/zsh
webproxy='/usr/local/www/apache24/data/des19/Data/Proxylist.txt';
resweb='/usr/local/www/apache24/data/des19/Data/Proxylist.txtupdated'
web='/usr/local/www/apache24/data/des19/Data/Proxystatus.log';
logging='/usr/local/www/apache24/data/des19/Data/currentinfo2.log';
licensename=`echo $@ | awk '{print $1}'`;
userreq=`echo $@  | awk '{print $2}'`;
privilege="Proxy";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
echo Adding Proxy License $licensename.... > $web;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='adding_Proxy_License:'$licensename;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging
isthere=`cat proxy.txt `
istheren=` echo $isthere | wc -c `
istheren=$((istheren+0));
if [[ $istheren -le 2 ]]; then
 isthere='n/a n/a n/a';
fi
proxyname=`echo $isthere | awk '{print $1}'`
aliasname=`echo $isthere | awk '{print $3}'`
newproxy=${proxyname}' '${licensename}' '${aliasname};
echo $newproxy > proxy.txt
./ProxyrcvInit.sh &
subres=`./jsonthis3.sh Proxyurl $proxyname License $licensename Alias $aliasname`
result='['${subres}']' ;
echo $result >$webproxy
resdate=`date +%s`;
res=` ./jsonthis3.sh updated $resdate`;
echo $res > $resweb;
echo Success Adding $licensename to proxy $proxyname > $web;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='success_adding_Proxy_license:'$licensename;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging
fi
bb=`cat $web`;
echo $datenow $timenow :$bb > ${logging}2
fi
