#! /usr/local/bin/zsh
webpartner='/usr/local/www/apache24/data/des19/Data/Partnerslist.txt';
resweb='/usr/local/www/apache24/data/des19/Data/Partnerslist.txtupdated'
web='/usr/local/www/apache24/data/des19/Data/Partnersstatus.log';
logging='/usr/local/www/apache24/data/des19/Data/currentinfo2.log';
echo $@ >> tmppartner
Partnername=`echo $@ | awk '{print $1}'`;
#type=`echo $@ | awk '{print $2}'`;
userreq=`echo $@  | awk '{print $2}'`;
privilege="Replication";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
echo Deleting partner $Partnername.... > $web;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Deleting_partner:'$Partnername;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging
partnerlist=`cat partners.txt `;
echo $partnerlist | grep "$Partnername" > txt/PartnerDel
echo $partnerlist | grep -v "$Partnername" > partners.txt
result="[";
cat partners.txt | while read -r line ; do
  n=` echo $line | awk '{print $1}'`;  
  t=`echo $line | awk '{print $2}'`;
  p=`echo $line | awk '{print $3}'`;
  subres=`./jsonthis3.sh name $n type $t proxy $p`;
  result=$result$subres,
done;
result=`echo $result | rev | cut -c 2- | rev`];
echo $result >$webpartner;
resdate=`date +%s`;
res=` ./jsonthis3.sh updated $resdate`;
echo $res > $resweb;
echo Success Deleting partner $Partnername > $web;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='success_Deleting_partner:'$Partnername;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging
bb=`cat $web`;
echo $datenow $timenow :$bb > ${logging}2
fi
