#!/usr/local/bin/zsh
cd /TopStor/;
websnaps='/var/www/html/des20/Data/Remoteperiodlist.txt';
resweb='/var/www/html/des20/Data/Remoteperiodlist.txtupdated';
txtres='/TopStordata/'`basename $0`$userreq'.txt'
echo $txtres
list=(`/usr/bin/crontab -l | grep -w RemoteSnapshotnowOnce  2>/dev/null`);
result='[';
echo "${list[@]}" | while read -r line;
do
 echo next line:
 echo $line
 line=`echo $line | awk -F "nowOnce" '{print $2}' `
 father2=`echo $line | awk '{print $1}' | awk -F/ '{print $2}' `;
 partner=` echo $line | awk '{print $3}'`;
 ts=` echo $line | awk '{print $2}'`;
 period2=`echo $ts | awk -F. '{print $1}' `;
 t1=` echo $ts  | awk -F. '{print $2}'`;	 
 t2=` echo $ts | awk -F. '{print $3}'`;
 t3=` echo $ts | awk -F. '{print $4}'`;
 t4=` echo $ts | awk -F. '{print $5}'`;
 subres=` /usr/local/bin/zsh jsonthis3.sh period $period2 father $father2 t1 $t1 t2 $t2 t3 $t3 t4 $t4 partner $partner` 
 result=$result$subres,
done
result=` echo $result | rev | cut -c 2- | rev`];
echo $result > $websnaps ;
resdate=`date +%s`;
res=`./jsonthis3.sh updated $resdate`;
echo $res > $resweb;
