#! /usr/local/bin/zsh
cd /TopStor
web='/usr/local/www/apache24/data/des19/Data/statusglobal.log';
oper=$@; 
oper1=`echo $oper | awk '{print $1}'`;
oper2=`echo $oper | awk '{print $2}'`;
oper3=`echo $oper | awk '{print $3}'`;
hostip=`ifconfig em1 | grep "inet " | awk '{print $2}'`;
pool=`echo $oper1 | awk -F/ '{print $1}'`;
vol=`echo $oper1 | awk -F/ '{print $2}'`;
stamp=`date +%s`;
newsnap2=`echo $oper2.$stamp`;
newsnap=`echo $oper1@$newsnap2`;
/sbin/zfs snapshot $newsnap; 
/sbin/zfs set repli:sender=$hostip $newsnap;
/sbin/zfs set repli:receiver=$oper3 $newsnap;
echo ./Replicate $hostip $oper3 txt/RemoteSnapshotnowOnce.txt$stamp $newsnap2 $pool $vol >> txt/tmprequest
./Replicate $hostip $oper3 txt/RemoteSnapshotnowOnce.txt$stamp $newsnap2 $pool $vol;
