#!/usr/local/bin/zsh
cd /TopStor
web='/usr/local/www/apache24/data/des19/Data/Replicatestatus.log'
logging='/usr/local/www/apache24/data/des19/Data/currentinfo2.log'
periodel=` echo $@ | awk '{print $1}'`;
userreq=` echo $@ | awk '{print $2}'`;
privilege="Replication";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Deleting_Period:'$periodel;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
echo Replica1003:$periodel > $web
/usr/bin/crontab -l | grep -v "$periodel" | /usr/bin/crontab -  2>txt/${0:2}$userreq.txt
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
err=`wc -c  txt/${0:2}$userreq.txt | awk '{print $1}'`;
if [[ $err -ge  4  ]]; then
        echo Replica1004:$periodel > $web;
        cat txt/${0:2}$userreq.txt > $web{internal};
        logdata='Failed_Deleting_Period:'$periodel;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
else
	 echo Replica1005:$periodel > $web;
        logdata='success_Deleting_Period:'$periodel;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
fi;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
rm txt/${0:2}$userreq.txt
./RemoteGetPoolperiodlist &
fi
bb=`cat $web`;
echo $datenow $timenow :$bb > ${logging}2
