#!/usr/local/bin/zsh
web='/usr/local/www/apache24/data/des19/Data/Replicatestatus.log';
logging='/usr/local/www/apache24/data/des19/Data/currentinfo2.log'
rm txt/cronthis.txt
stime=`echo $@ | awk '{print $1}'`;
hr=`echo $stime | awk -F: '{print $1}'`;
min=`echo $stime | awk -F: '{print $2}'`;
every=`echo $@ | awk '{print $2}'` ;
k=0; keep=`echo $@ | awk '{print $3}'`; keep=$(($keep+$k)); if (($keep < 1)); then keep=1; fi
DG=` echo $@ | awk '{print $4}'`; 
FileS=` echo $@ | awk '{print $5}'`;
partner=` echo $@ | awk '{print $6}'`;
userreq=` echo $@ | awk '{print $7}'`;
privilege="Replication";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
echo Replica1019: > $web;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Creating_Weekly_Preiod:'$DG/$FileS'_to_'$partner;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
crontab -l > txt/cronthis.txt
echo $min  $hr "*" "*" $every  /TopStor/pump.sh RemoteSnapshotnow $DG/$FileS Weekly.$keep.$hr.$min.$every $partner 2>txt/SnapshotnowSystem.txt >> txt/cronthis.txt
crontab txt/cronthis.txt 2>>txt/${0:2}$userreq.txt
err=`wc -c  txt/${0:2}$userreq.txt | awk '{print $1}'`;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
if [[ $err -ge  4  ]]; then
	echo Replica1020: > $web;
	cat txt/${0:2}$userreq.txt > ${web}internal;
	logdata='Failed_Creating_Weekly_Replication_Period:'$DG/$FileS'_for_'$partner;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg error user $userreq data $logdata`;
else 
	echo Replica1021:Weekly.$hr.$min.$every.$keep:$partner:$DG/$FileS > $web; 
	logdata='Success_Creating_Weekly_Replication_Period:'$DG/$FileS'_for_'$partner;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
fi;
rm txt/${0:2}$userreq.txt
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
./RemoteGetPoolperiodlist 
fi
bb=`cat $web`;
echo $datenow $timenow :$bb > ${logging}2
