#! /usr/local/bin/zsh
cd /TopStor
oper=$@; 
oper1=`echo $oper | awk '{print $1}'`;
oper2=`echo $oper | awk '{print $2}'`;
oper3=`echo $oper | awk '{print $3}'`;
errf=`echo $oper | awk '{print $4}'`;
hostip=`ifconfig em1 | grep "inet " | awk '{print $2}'`;
pool=`echo $oper1 | awk -F/ '{print $1}'`;
vol=`echo $oper1 | awk -F/ '{print $2}'`;
stamp=`date +%s`;
newsnap2=`echo $oper2.$stamp`;
newsnap=`echo $oper1@$newsnap2`;
/sbin/zfs snapshot $newsnap; 
/sbin/zfs set repli:sender=$hostip $newsnap;
/sbin/zfs set repli:receiver=$oper3 $newsnap;
isproxy=`cat partners.txt | grep $oper3 | awk '{print $3}'`;
if [[ $isproxy == "true" ]];
then
##########with proxy##################################################o
## $hostip $oper3 txt/RemoteSnapshotnowOnce.txt$stamp $newsnap2 $pooli $vol $remotetun $pp $so
############################################################3
  #./ProxysndSVC.sh
  so=`cat proxy.txt | awk '{print $3}'`
  remotetun=`cat txt/receiver | grep "$oper3" | awk '{print $3}'`
  pp=`cat workingpp | awk '{print $1}'`
  /sbin/zfs set repli:sender=$so $newsnap;
 echo  running ./ProxyReplicate $oper3 $errf $newsnap2 $pool $vol $remotetun $pp $so >> txt/tmpproxyrequest;
 ./ProxyReplicate $oper3 $errf $newsnap2 $pool $vol $remotetun $pp $so;
##########noproxy####################################################
else
 echo ./Replicate $hostip $oper3 $errf $newsnap2 $pool $vol >> txt/tmprequest
 ./Replicate $hostip $oper3 $errf $newsnap2 $pool $vol;
fi
 #echo donereplicating
