#!/usr/local/bin/zsh
cd /TopStor
web='/usr/local/www/apache24/data/des19/Data/Replicatestatus.log';
logging='/usr/local/www/apache24/data/des19/Data/currentinfo2.log'
snapdel=` echo $@ | awk '{print $1}'`;
userreq=` echo $@ | awk '{print $2}'`;
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Deleting_Snapshot:'$snapdel;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
echo Replica1000:$snapdel > $web;
/sbin/zfs destroy $snapdel  2>txt/${0:2}$userreq.txt;
err=`wc -c  txt/${0:2}$userreq.txt | awk '{print $1}'`;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
if [[ $err -ge  4  ]]; then
	echo Replica1001:$snapdel > $web;
	cat txt/${0:2}$userreq.txt > ${web}internal;
	logdata='Failed_Deleting_Snapshot:'$snapdel;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg error user $userreq data $logdata`;
else 
	 echo Replica1002:$snapdel > $web; 
	logdata='Success_Deleting_Snapshot:'$snapdel;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
fi;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
rm txt/${0:2}$userreq.txt
./GetSnaplist
fi
bb=`cat $web`;
echo $datenow $timenow :$bb > ${logging}2
