#!/usr/local/bin/zsh
cd /TopStor
web='/usr/local/www/apache24/data/des19/Data/Replicatestatus.log';
logging='/usr/local/www/apache24/data/des19/Data/currentinfo2.log'
rm txt/cronthis.txt
every=0; ev=`echo $@ | awk '{print $1}'`; every=$(($every+$ev)) ; if (($every < 1)); then every=1; fi
keep=0; k=`echo $@ | awk '{print $2}'`; keep=$(($keep+$k)); if (($keep < 1)); then keep=1 ; fi
DG=` echo $@ | awk '{print $3}'`; 
FileS=` echo $@ | awk '{print $4}'`;
partner=` echo $@ | awk '{print $5}'`;
userreq=` echo $@ | awk '{print $6}'`;
privilege="Replication";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
echo Repica1016: > $web;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Creating_Minutely_Replication_Period:'$DG/$FileS'_to_'$partner;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
crontab -l > txt/cronthis.txt
echo "*"/$every "*" "*" "*" "*"  /TopStor/pump.sh RemoteSnapshotnow $DG/$FileS Minutely.$keep.$every.na.na $partner 2> txt/err.txt >> txt/cronthis.txt
crontab txt/cronthis.txt 2>>txt/${0:2}$userreq.txt
err=`wc -c  txt/${0:2}$userreq.txt | awk '{print $1}'`;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
if [[ $err -ge  4  ]]; then
	echo Replica1017: > $web;
	cat txt/${0:2}$userreq.txt > ${web}internal;
	logdata='Failed_Creating_Minutely_Replication_Period:'$DG/$FileS'_for:'$partner;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg error user $userreq data $logdata`;
else 
 echo Replica1018:Minutely.$every.$keep:$partner:$DG/$FileS > $web; 
	logdata='Success_Creating_Minutely_Replication_Period:'$DG/$FileS'_for_'$partner;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
fi;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
./RemoteGetPoolperiodlist
fi
bb=`cat $web`;
echo ${datenow} ${timenow} :${bb} > ${logging}2
rm txt/${0:2}$userreq.txt
