#!/usr/local/bin/zsh
cd /TopStor
web='/var/www/html/des20/Data/Replicatestatus.log'
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/TopStordata/TopStor.log';
txtres='/TopStordata/'`basename $0`$userreq'.txt'
rm $txtres 2>/dev/null
periodel=` echo $@ | awk '{print $1}'`;
userreq=` echo $@ | awk '{print $2}'`;
privilege="Replication";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Deleting_Period:'$periodel;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Replica1045@@@$periodel`;
echo Replica1045@$datenow@$timenow@$periodel > ${logging}2
echo $datenow $timenow info Replica1045@$datenow@$timenow@$periodel >> $glog
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
echo Replica1003:$periodel > $web
echo $periodel
/usr/bin/crontab -l | grep -v "$periodel" | /usr/bin/crontab -  2> $txtres
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
err=`wc -c  $txtres | awk '{print $1}'`;
if [[ $err -ge  4  ]]; then
        echo Replica1004:$periodel > $web;
        cat $txtres > ${web}internal;
        logdata='Failed_Deleting_Period:'$periodel;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg error user $userreq data $logdata code Replica1046@@@$periodel`;
echo Replica1046@$datenow@$timenow@$periodel > ${logging}2
echo $datenow $timenow error Replica1046@$datenow@$timenow@$periodel >> $glog
else
	 echo Replica1005:$periodel > $web;
        logdata='success_Deleting_Period:'$periodel;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Replica1047@@@$periodel`;
echo Replica1047@$datenow@$timenow@$periodel > ${logging}2
echo $datenow $timenow info Replica1047@$datenow@$timenow@$periodel >> $glog
fi;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
./RemoteGetPoolperiodlist &
fi
