#! /usr/local/bin/zsh
web='/usr/local/www/apache24/data/des19/Data/Replicatestatus.log';
logging='/usr/local/www/apache24/data/des19/Data/currentinfo2.log'
echo Creating  snapshot.... > $web;
name=`echo $@ | awk '{print $1}'`;
DG=`echo $@ | awk '{print $2}'`;
FileS=` echo $@ | awk '{print $3}'`;
partner=` echo $@ | awk '{print $4}'`;
userreq=` echo $@ | awk '{print $5}'`;
privilege="Replication";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
echo Replicating_manually:'$DG/$FileS' to'$partner > $web;
logdata='Replicating_manually:'$DG/$FileS' to'$partner;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
echo /TopStor/RemoteSnapshotnowOnce $DG/$FileS $name. $partner 2> txt/$0$userreq.txt 
/TopStor/RemoteSnapshotnowOnce $DG/$FileS $name. $partner 2> txt/$0$userreq.txt 
err=`wc -c  txt/$0$userreq.txt | awk '{print $1}'`;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
if [[ $err -ge  4  ]]; then
	cat txt/$0$userreq.txt > $web;
	logdata='Failed_Replicating_manually:'$DG/$FileS' to'$partner;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg error user $userreq data $logdata`;
else 
 	echo DONE...Replicating_manually:$DG/$FileS to $partner > $web; 
	logdata='Success_Replicating_manually:'$DG/$FileS' to'$partner;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
fi;
rm txt/$0$userreq.txt
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
fi
bb=`cat $web`;
echo $datenow $timenow :$bb > ${logging}2
