#! /usr/local/bin/zsh
cd /TopStor
web='/usr/local/www/apache24/data/des19/Data/Snapsstatus.log';
logging='/usr/local/www/apache24/data/des19/Data/currentinfo2.log'
rm txt/cronthis.txt
every=0; ev=`echo $@ | awk '{print $1}'`; every=$(($every+$ev)) ; if (($every < 1)); then every=1; fi
keep=0; k=`echo $@ | awk '{print $2}'`; keep=$(($keep+$k)); if (($keep < 1)); then keep=1 ; fi
DG=` echo $@ | awk '{print $3}'`; 
FileS=` echo $@ | awk '{print $4}'`;
userreq=` echo $@ | awk '{print $5}'`;
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
echo Adding snapshot schedule.... > $web;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Creating_MinutelyPeriod:'$DG/$FileS@$name;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
crontab -l > txt/cronthis.txt
echo "*"/$every "*" "*" "*" "*"  /TopStor/pump.sh Snapshotnow $DG/$FileS Minutely.$keep.$every.na.na 2> txt/err.txt >> txt/cronthis.txt
crontab txt/cronthis.txt 2>>txt/$0$userreq.txt
err=`wc -c  txt/$0$userreq.txt | awk '{print $1}'`;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
if [[ $err -ge  4  ]]; then
	cat txt/$0$userreq.txt > $web;
	logdata='Failed_Creating_MinutelyPeriod:'$DG/$FileS@$name;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg error user $userreq data $logdata`;
else 
 echo DONE...Snapshot Minutely.$every.$keep is added > $web; 
	logdata='Success_Creating_MinutelyPeriod:'$DG/$FileS@$name;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
fi;
rm txt/$0$userreq.txt
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
./GetPoolperiodlist
fi
bb=`cat $web`;
echo ${datenow} ${timenow} :${bb} > ${logging}2
echo ${datenow} ${timenow} > txt/tmpm
