#!/usr/local/bin/zsh
cd /TopStor
so=`echo $@ | awk '{print $1}'`;
dst=`echo $@ | awk '{print $2}'`;

snap=`echo $@ | awk '{print $3}'`
pool=`echo $@ | awk '{print $4}'`;
vol=`echo $@ | awk '{print $5}'`;
pp=$(( 3000+( $(od -An -N2 -i /dev/random) )%(4000-1024+1) ))
#nc -l 3333 |  gunzip | openssl enc -d  -a -A -aes-256-cbc -k SuperSecretPWD | zfs receive -d  Data

volfound=`./Remoterequest.sh $so $dst rep RemoteVolSearch $vol | awk '{print $2}'`;
if [[ $volfound == "no" ]];
then
 volpar=`./RemoteGetPoolVollist $vol`;
 prot=`echo $volpar | awk '{print $1}'`;
 size=`echo $volpar | awk '{print $2}'`;
 echo param=$volpar
 ./Remoterequest.sh $so $dst nop VolumeCreate$prot $pool $vol ${size}M admin; 
 echo  $so $dst nop VolumeCreate$prot $pool $vol ${size}M admin 
sleep 20;
 ./Remoterequest.sh $so $dst nop repli.sh $pp $pool ;
 ./Remoterequest.sh $so $dst nop GetPoolVollist hi & 
 zfs send -D $pool/$vol@$snap  | openssl enc -a -A -aes-256-cbc -k SuperSecretPWD | gzip -cf | nc -N  $dst $pp ;
else if [[ $volfound == "found" ]];
then
oldsnaps=`./Remoterequest.sh $so $dst rep RemoteGetSnaplist $vol`;
localsnaps=`./RemoteGetSnaplist $vol`;
ll=`echo $oldsnaps | awk '{$1=""; print substr ($0,2)}'`;
ll=${ll}' spot';
lineupsnaps=`echo $ll | tr ' ' '\n' `
initialsnap="";
echo $lineupsnaps | while read -r line  
do
 if [[ ${localsnaps/$line} == $localsnaps ]]; then ; else initialsnap=$line;  break; fi;
done;
targetsnap=$pool/$vol@$snap;
if [[ $initialsnap == $targetsnap ]]; then echo up-to-date ; else 
 ./Remoterequest.sh $so $dst nop repli.sh $pp $pool ;
 zfs send -R -I $initialsnap  $targetsnap  | openssl enc -a -A -aes-256-cbc -k SuperSecretPWD | gzip -cf | nc -N  $dst $pp
fi
fi
fi
 ./Remoterequest.sh $so $dst nop GetSnaplist hi & 
