#!/usr/local/bin/zsh
cd /TopStor
so=`echo $@ | awk '{print $1}'`;
dst=`echo $@ | awk '{print $2}'`;

snap=`echo $@ | awk '{print $3}'`
pool=`echo $@ | awk '{print $4}'`;
vol=`echo $@ | awk '{print $5}'`;
prot=`echo $@ | awk '{print $6}'`;
size=`echo $@ | awk '{print $7}'`;
pp=$(( 3000+( $(od -An -N2 -i /dev/random) )%(4000-1024+1) ))
#nc -l 3333 |  gunzip | openssl enc -d  -a -A -aes-256-cbc -k SuperSecretPWD | zfs receive -d  Data

volfound=`./Remoterequest.sh $so $dst RemoteVolSearch $vol | awk '{print $2}'`;
if [[ $volfound == "no" ]];
then
 ./Remoterequest.sh $so $dst VolumeCreate$prot $pool $vol ${size}G admin; 
 sleep 2;
 ./Remoterequest.sh $so $dst runny.sh /usr/bin/nc -l $pp | gunzip | openssl enc -d  -a -A -aes-256-cbc -k SuperSecretPWD | zfs receive -d  Data \&;
 sleep 3;
 zfs send -D $pool/$vol@$snap  | openssl enc -a -A -aes-256-cbc -k SuperSecretPWD | gzip -cf | nc -N  $dst $pp 
fi
 
 
