#!/usr/local/bin/zsh
web='/usr/local/www/apache24/data/des19/Data/CIFSstatus.log';
logging='/usr/local/www/apache24/data/des19/Data/currentinfo2.log'
cd /TopStor
name=`echo $@ | awk '{print $1}'`;
g=`cat smb4.confcurrent | grep ${name}_only | wc -c`; if [[ g -le 4 ]];
then
 cp /usr/local/etc/smb4.conf smb4.confcurrent;
 sleep 1;
 sed -e "s/NAMECIFS/$name/g" sharecifs.txt > $name.txt;
 cat $name.txt >> smb4.confcurrent;
 cat $name.txt >> CIFSshares.txt;
 cat $name.txt >> /usr/local/etc/smb4.conf ;
 service samba_server restart;
fi
