#!/usr/local/bin/zsh
cd /TopStor
export POR;
export RR; 
function Remoteinitialize() {
 so=`echo $@ | awk '{print $1}'`;
 dst=`echo $@ | awk '{print $2}'`;
 reply=`echo $@ | awk '{print $3}'`;
 pp2=`echo $@ | awk '{print $5}'`;
 msg=`echo $@ | awk '{$1=$2=$3=""; print substr($0,4)}'`
 lineflag="failed"
 stamp=`date +%s`
 read -t 2  line < /tmp/msgrack ;
 flagcount=0;
 echo initxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx >> txt/tmprequest
 while [[ $lineflag == "failed" && flagcount -le 5 ]]; do
 {
  echo echo $so $stamp $reply $msg \| openssl enc -a -A -aes-256-cbc -k SuperSecretPWD \| gzip -cf \| nc -N  $dst  2234 >> txt/tmprequest
  echo $so $stamp $reply $msg | openssl enc -a -A -aes-256-cbc -k SuperSecretPWD | gzip -cf | nc -N  $dst  2234
  read -t 2 line < /tmp/msgrack ;
  stampreply=`echo $line | awk '{print $1}'`;
  flagcount=$((flagcount+1));
  if [[ $stampreply == $stamp ]]; then echo line=$line >> txt/tmprequest; lineflag=`echo $line | awk '{$1=$2="";print substr($0,3)}'`;  fi 
  echo initloopline=$lineflag >> txt/tmprequest
 }
 done;
 POR=`echo waiting | nc -N $dst $pp2`;
 echo initafterrequest=$POR >> txt/tmprequest
}
#############################################################################33
function RemoteAsk() {
 dst=`echo $@ | awk '{print $1}'`;
 msg=`echo $@ | awk '{$1=""; print substr($0,2)}'`
 flagcount=0;
 echo RemoteAskxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx >> txt/tmprequest
 lineflag=`echo $msg | nc -N  $dst $POR `; 
 lineflagn=`echo $lineflag | wc -c `;
  echo lineflag=$lineflag  linen=$lineflagn count=$flagcount >> txt/tmprequest
 while [[ $lineflagn -le 2 && $flagcount -le 20 ]]; do
 {
  sleep 1
 lineflag=`echo waiting | nc -N $dst $POR`;
 lineflagn=`echo $lineflag | wc -c `;
  flagcount=$((flagcount+1));
  echo lineflag=$lineflag  linen=$lineflagn count=$flagcount >> txt/tmprequest
 }
 done;
 if [[ $lineflag == "waiting" ]]; then RR="FAILED"; else RR=$lineflag; fi;
 echo afterAsk=$RR >> txt/tmprequest
 #echo $lineflag;
}
###############################################################################
#########################################################################
###############################################################################
so=`echo $@ | awk '{print $1}'`;
dst=`echo $@ | awk '{print $2}'`;
filelog=`echo $@ | awk '{print $3}'`;
snap=`echo $@ | awk '{print $4}'`
pool=`echo $@ | awk '{print $5}'`;
vol=`echo $@ | awk '{print $6}'`;
pp=$(( 3000+( $(od -An -N2 -i /dev/random) )%(4000-1024+1) ))
pt=$(( pp+1 ));
echo Replicate=$RR >> txt/tmprequest
echo Roperands=$@ >> txt/tmprequest;
Remoteinitialize $so $dst nop ReInit.sh $pp ;
echo pp=$pp while POR=$POR >> txt/tmprequest
if [[ $POR != "waiting" ]]; then echo cannot make session;
else 
 POR=$pp;
 echo RemoteAsk $dst RemoteVolSearch $vol >> txt/tmprequest
 RemoteAsk $dst RemoteVolSearch $vol;
 volfound=$RR;
 echo volfound=$volfound >> txt/tmprequest
 if [[ $volfound == 'FAILED' ]]; then echo Problem: $volfound >> $filelog; exit 1 ; fi
 if [[ $volfound == "no" ]];
 then
  echo no >> txt/tmprequest
  volpar=`./RemoteGetPoolVollist $vol`;
  prot=`echo $volpar | awk '{print $1}'`;
  size=`echo $volpar | awk '{print $2}'`;
  echo RemoteAsk $dst VolumeCreate$prot $pool $vol ${size}M admin >> txt/tmprequest 
  RemoteAsk $dst VolumeCreate$prot $pool $vol ${size}M admin; 
  echo RemoteAsk $dst repli.sh $pt $pool $so $vol >> txt/tmprequest;
  tobeready=`RemoteAsk $dst repli.sh $pt $pool $so $vol` ;
#  echo RemoteAsk $dst GetPoolVollist hi  >> txt/tmprequest; 
#  RemoteAsk $dst GetPoolVollist hi  
  echo zfs send -D $pool/$vol@$snap  \| openssl enc -a -A -aes-256-cbc -k SuperSecretPWD \| gzip -cf \| nc -N  $dst $pt  >> txt/tmprequest;
  zfs send -D $pool/$vol@$snap  | openssl enc -a -A -aes-256-cbc -k SuperSecretPWD | gzip -cf | nc -N  $dst $pt ;
 else 
  if [[ $volfound == "found" ]];
  then
   echo foundfoundfoundfoudnfoundofudnffoudnsdoufndfousdn >> txt/tmprequest
   RemoteAsk $dst RemoteGetSnaplist $vol;
   oldsnaps=$RR
   localsnaps=`./RemoteGetSnaplist $vol`;
   ll=$oldsnaps;
   ll=${ll}' spot';
   echo ll=$ll >> txt/tmprequest
   lineupsnaps=`echo $ll | tr ' ' '\n' `
   initialsnap="";
   echo $lineupsnaps | while read -r line  
   do
    if [[ ${localsnaps/$line} == $localsnaps ]];
    then ; else initialsnap=$line;  break; fi;
   done;
   targetsnap=$pool/$vol@$snap
   echo targetsnap=$targetsnap >> txt/tmprequest
   echo initialsnap=$initialsnap >> txt/tmprequest
   if [[ $initialsnap == $targetsnap ]]; 
   then echo up-to-date >> txt/tmprequest; fi
   if [[ $initialsnap == "" ]];
   then 
    echo yyyyyyyyyyyyyintital is null >> txt/tmprequest 
    echo RemoteAsk $dst destroysnaps.sh $vol >> txt/tmprequest;
    RemoteAsk $dst destroysnaps.sh $vol ;
    echo RemoteAsk $dst repli.sh $pt $pool $so $voli >> txt/tmprequest;
    RemoteAsk $dst repli.sh $pt $pool $so $vol;
    echo zfs send -R   $targetsnap  \| openssl enc -a -A -aes-256-cbc -k SuperSecretPWD \| gzip -cf \| nc -N  $dst $pt >> txt/tmprequest
    zfs send -R   $targetsnap  | openssl enc -a -A -aes-256-cbc -k SuperSecretPWD | gzip -cf | nc -N  $dst $pt;
   else
    echo RemoteAsk $dst repli.sh $pt $pool $so $vol >> txt/tmprequest;
    RemoteAsk $dst repli.sh $pt $pool $so $vol;
    zfs send -R -I $initialsnap  $targetsnap  | openssl enc -a -A -aes-256-cbc -k SuperSecretPWD | gzip -cf | nc -N  $dst $pt;
   fi
  fi
 fi
 ./GetSnaplist & 
 echo RemoteAsk $dst GetSnaplist hi  >> txt/tmprequest 
 RemoteAsk $dst GetSnaplist hi  
fi
 echo POR=$POR RemoteAsk $dst done >> txt/tmprequest ; 
 RemoteAsk $dst done  & ; 
