#! /usr/local/bin/zsh
cd /TopStor
# command is newcom paramaters (at least one)
echo $@ > tmprep2
sendertun=`echo  $@ | awk '{print $1}'`;
sender=`echo  $@ | awk '{print $2}'`;
replier=`echo  $@ | awk '{print $3}'`;
senderpp=`echo  $@ | awk '{print $4}'`;
pp=`echo  $@ | awk '{print $5}'`;
tun=`echo  $@ | awk '{print $6}'`;
stamp=`echo  $@ | awk '{print $7}'`;
localrep=`echo  $@ | awk '{print $8}'`;
newcom=`echo  $@ | awk '{print $9}'`;
param=`echo  $@ | awk '{$1=$2=$3=$4=$5=$6=$7=$8=$9="";print substr($0,10)}'`;
# packet : sender stamp command
fileres='txt/runthis'$stamp
echo $localrep > $fileres
isvalid=`cat Commands.txt | grep "$newcom"`
if [[ $? -eq 0 ]];
then 
 validcom=${isvalid}" "${fileres}" "$param;
 echo isvalidcome=$validcom  > tmp2runthis 
 ./$validcom 2>> tmp2runthis
# ./${isvalid} ${fileres} $param 2>/tmp2runthis
 echo ran the command > tmp3runthis
 while [[ ! -a $fileres ]];  
 do
  c=0;  while [[ $c -le 30 ]]; do c=$((c+1)); done
 done
 res=`cat $fileres`
 echo res=$res >> tmp2runthis
 rm $fileres 2>/dev/null
# ppp=$((senderpp+1));
 ppp=$senderpp
 echo Askreply $replier $sendertun $ppp $localrep reply $res >> tmp2runthis
 ./Askreply $replier $sendertun $ppp $localrep reply $res
fi
echo isvalid=$isvalid  >> tmp2runthis 
