#! /usr/local/bin/zsh
cd /TopStor
web='/usr/local/www/apache24/data/des19/Data/status.log'
logging='/usr/local/www/apache24/data/des19/Data/currentinfo2.log'
periodel=` echo $@ | awk '{print $1}'`;
userreq=` echo $@ | awk '{print $2}'`;
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Deleting_Period:'$periodel;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
echo Deleteing Preiod $periodel > $web
/usr/bin/crontab -l | grep -v "$periodel" | /usr/bin/crontab -  2>txt/$0$userreq.txt
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
err=`wc -c  txt/$0$userreq.txt | awk '{print $1}'`;
if [[ $err -ge  4  ]]; then
        cat txt/$0$userreq.txt > $web;
        logdata='Failed_Deleting_Period:'$periodel;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
else
	 echo DONE...Period $periodel is deleted > $web;
        logdata='success_Deleting_Period:'$periodel;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
fi;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
rm txt/$0$userreq.txt
./GetPoolperiodlist
fi
