#!/usr/local/bin/zsh
cd /TopStor
web='/var/www/html/des20/Data/Snapsstatus.log'
logging='/var/www/html/des20/Data/currentinfo2.log'
periodel=` echo $@ | awk '{print $1}'`;
userreq=` echo $@ | awk '{print $2}'`;
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Deleting_Period:'$periodel;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Snap1043@@@$periodel`;
echo Snap1043@$datenow@$timenow@$periodel > ${logging}2
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
echo Snap1003:$periodel > $web
/usr/bin/crontab -l | grep -v "$periodel" | /usr/bin/crontab -  2>txt/${0:2}$userreq.txt
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
err=`wc -c  txt/${0:2}$userreq.txt | awk '{print $1}'`;
if [[ $err -ge  4  ]]; then
        echo Snap1004:$periodel > $web;
        cat txt/${0:2}$userreq.txt > ${web}internal;
        logdata='Failed_Deleting_Period:'$periodel;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Snap1044@@@$periodel`;
echo Snap1044@$datenow@$timenow@$periodel > ${logging}2
else
	 echo Snap1005:$periodel > $web;
        logdata='success_Deleting_Period:'$periodel;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata Snap1045@@@$periodel`;
echo Snap1045@$datenow@$timenow@$periodel > ${logging}2
fi;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
rm txt/${0:2}$userreq.txt
./GetPoolperiodlist
fi
