#!/usr/local/bin/zsh
cd /TopStor
web='/usr/local/www/apache24/data/des19/Data/Snapsstatus.log';
logging='/usr/local/www/apache24/data/des19/Data/currentinfo2.log'
snaprol=` echo $@ | awk '{print $1}'`;
userreq=` echo $@ | awk '{print $2}'`;
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Rollingback_Snapshot:'$snaprol;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
echo Snap1006:$snaprol > $web;
/sbin/zfs rollback -r  $snaprol  2>txt/${0:2}$userreq.txt;
err=`wc -c  txt/${0:2}$userreq.txt | awk '{print $1}'`;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
if [[ $err -ge  4  ]]; then
	echo Snap1007:$snaprol > $web;
	cat txt/${0:2}$userreq.txt > ${web}internal;
	logdata='Failed_Rollingback_Snapshot:'$snaprol;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg error user $userreq data $logdata`;
else 
	echo Snap1008:$snaprol > $web; 
	logdata='Success_Rollingback_Snapshot:'$snaprol;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
fi;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
rm txt/${0:2}$userreq.txt
./GetSnaplist
fi
bb=`cat $web`;
echo $datenow $timenow :$bb > ${logging}2
