#!/usr/local/bin/zsh
web='/usr/local/www/apache24/data/des19/Data/Snapsstatus.log';
logging='/usr/local/www/apache24/data/des19/Data/currentinfo2.log'
rm txt/cronthis.txt
stime=`echo $@ | awk '{print $1}'`;
hr=`echo $stime | awk -F: '{print $1}'`;
min=`echo $stime | awk -F: '{print $2}'`;
every=`echo $@ | awk '{print $2}'` ;
k=0; keep=`echo $@ | awk '{print $3}'`; keep=$(($keep+$k)); if (($keep < 1)); then keep=1; fi
DG=` echo $@ | awk '{print $4}'`; 
FileS=` echo $@ | awk '{print $5}'`;
userreq=` echo $@ | awk '{print $6}'`;
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
echo Adding snapshot schedule.... > $web;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Creating_WeeklyPreiod:'$DG/$FileS;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
crontab -l > txt/cronthis.txt
echo $min  $hr "*" "*" $every  /TopStor/pump.sh Snapshotnow $DG/$FileS Weekly.$keep.$hr.$min.$every 2>txt/SnapshotnowSystem.txt >> txt/cronthis.txt
crontab txt/cronthis.txt 2>>txt/${0:2}$userreq.txt
err=`wc -c  txt/${0:2}$userreq.txt | awk '{print $1}'`;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
if [[ $err -ge  4  ]]; then
	cat txt/${0:2}$userreq.txt > $web;
	logdata='Failed_Creating_WeeklyPeriod:'$DG/$FileS;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg error user $userreq data $logdata`;
else 
	echo DONE...Snapshot Weekly.$hr.$min.$every.$keep is added > $web; 
	logdata='Success_Creating_WeeklyPeriod:'$DG/$FileS;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
fi;
rm txt/${0:2}$userreq.txt
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
./GetPoolperiodlist 
fi
bb=`cat $web`;
echo $datenow $timenow :$bb > ${logging}2
