#! /usr/local/bin/zsh
cd /TopStor
web='/usr/local/www/apache24/data/des19/Data/status.log'
echo Deleteing Preiod $@ > $web
/usr/bin/crontab -l | grep -v "$@" | /usr/bin/crontab -
echo Preiod $@ is deleted > $web
./GetPoolperiodlist
