#!/usr/local/bin/zsh
cd /TopStor
web='/var/www/html/des20/Data/statusglobal.log';
oper=$@; 
sshost=`echo $@ | awk '{print $1}'`;
hostnam=`echo $@ | awk '{print $2}'`;
oper1=`echo $oper | awk '{print $3}'`;
oper2=`echo $oper | awk '{print $4}'`;
echo creating Snapshot $hostnam $oper1 $oper2.... > $web;
stamp=`date +%s`;
newsnap2=`echo $oper2.$stamp`;
newsnap=`echo $oper1@$newsnap2`;
echo ssh root@$sshost \"/sbin/zfs snapshot $newsnap\"  txt/err.txt
ssh root@$sshost /sbin/zfs snapshot $newsnap 2>> txt/err.txt
err=`wc -c  txt/err.txt | awk '{print $1}'`;
if [[ $err >  4  ]]; then
	cat txt/err.txt >> $web;
	cat txt/err.txt
else 
timenow=`/usr/bin/date`
echo $timenow: DONE...Snapshot $newsnap is created >> $web; 
echo $timenow: DONE...Snapshot $newsnap is created  $web; 
./GetSnaplist
echo OK;
fi;
#sleep 2;
