#!/usr/local/bin/zsh
web='/usr/local/www/apache24/data/des19/Data/Snapsstatus.log';
logging='/usr/local/www/apache24/data/des19/Data/currentinfo2.log'
echo Snap1012: > $web;
name=`echo $@ | awk '{print $1}'`;
DG=`echo $@ | awk '{print $2}'`;
FileS=` echo $@ | awk '{print $3}'`;
userreq=` echo $@ | awk '{print $4}'`;
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
echo Snap1013:$DG/$FileS > $web;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Creating_Snapshot:'$DG/$FileS@$name;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Snap1026@@@$DG/$FileS@name`;
echo Snap1026@$datenow@$timenow@$DG/$FileS@$name > ${logging}2
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
/TopStor/SnapshotnowOnce $DG/$FileS $name. 2> txt/${0:2}$userreq.txt 
err=`wc -c  txt/${0:2}$userreq.txt | awk '{print $1}'`;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
if [[ $err -ge  4  ]]; then
	echo Snap1014:$DG/$FileS > $web;
	cat txt/${0:2}$userreq.txt > $web;
	logdata='Failed_Creating_Snapshot:'$DG/$FileS@$name;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg error user $userreq data $logdata Snap1028@@@$DG/$FileS@$name`;
echo Snap1028@$datenow@$timenow@$DG/$FileS@$name > ${logging}2
else 
 	echo Snap1015:$DG/$FileS$name.$now1 > $web; 
	logdata='Success_Creating_Snapshot:'$DG/$FileS@$name;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Snap1030@@@$DG/$FileS@$name`;
echo Snap1030@$datenow@$timenow@$DG/$FileS@$name > ${logging}2
fi;
rm txt/${0:2}$userreq.txt
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
./GetSnaplist
fi
