#!/usr/local/bin/zsh
cd /TopStor/
web='/var/www/html/des20/Data/Snapsstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
runningpools='/pacedata/pools/runningpools'
pDG=` echo $@ | awk '{print $1}'`;
snaprol=` echo $@ | awk '{print $2}'`;
userreq=` echo $@ | awk '{print $3}'`;
txtres=txt/`basename $0`$userreq.txt
rm  $txtres 2>/dev/null
hostnam=` echo $pDG | awk -F_ '{print $1}'`;
sshost=`cat $runningpools | grep $hostnam | awk '{print $1}'`;
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Rollingback_Snapshot:'$hostnam/$snaprol;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Snap1040@@@$hostnam/$snaprol`;
echo Snap1040@$datenow@$timenow@$hostnam/$snaprol > ${logging}2
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
echo Snap1006:$hostnam/$snaprol > $web;
ssh root@$sshost "/sbin/zfs rollback -r  $snaprol"  2> $txtres;
err=`wc -c  $txtres | awk '{print $1}'`;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
if [[ $err -ge  4  ]]; then
	echo Snap1007:$hostnam/$snaprol > $web;
	cat $txtres > ${web}internal;
	logdata='Failed_Rollingback_Snapshot:'$hostnam/$snaprol;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg error user $userreq data $logdata code Snap1041@@@$hostnam/$snaprol`;
echo Snap1041@$datenow@$timenow@$hostnam/$snaprol > ${logging}2
else 
	echo Snap1008:$hostnam/$snaprol > $web; 
	logdata='Success_Rollingback_Snapshot:'$hostnam/$snaprol;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Snap1042@@@$hostnam/$snaprol`;
echo Snap1042@$datenow@$timenow@$hostnam/$snaprol > ${logging}2
./GetSnaplist
fi;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
fi
