#!/usr/local/bin/zsh
cd /TopStor/
web='/var/www/html/des20/Data/Snapsstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
runningpools='/pacedata/pools/runningpools'

echo Snap1012: > $web;
name=`echo $@ | awk '{print $1}'`;
pDG=`echo $@ | awk '{print $2}'`;
FileS=` echo $@ | awk '{print $3}'`;
userreq=` echo $@ | awk '{print $4}'`;
txtres=txt/`basename $0`$userreq.txt
rm $txtres 2>/dev/null
DG=`echo $pDG | awk -F_ '{print $2}'`;
hostnam=`echo $pDG | awk -F_ '{print $1}'`;
sshost=`cat $runningpools | grep $hostnam | awk '{print $1}'`;
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
echo Snap1013:$hostnam/$DG/$FileS > $web;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Creating_Snapshot:'$DG/$FileS@$name;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Snap1026@@@$hostnam/$DG/$FileS@name`;
echo Snap1026@$datenow@$timenow@$hostnam/$DG/$FileS@$name > ${logging}2
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
/TopStor/SnapshotnowOnce $sshost $hostnam $DG/$FileS $name. 2> $txtres
err=`wc -c  $txtres | awk '{print $1}'`;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
if [[ $err -ge  4  ]]; then
	echo Snap1014:$hostnam/$DG/$FileS > $web;
	cat $txtres > $web;
	logdata='Failed_Creating_Snapshot:'$hostnam/$DG/$FileS@$name;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg error user $userreq data $logdata Snap1028@@@$hostnam/$DG/$FileS@$name`;
echo Snap1028@$datenow@$timenow@$hostnam/$DG/$FileS@$name > ${logging}2
else 
 	echo Snap1015:$hostnam/$DG/$FileS$name.$now1 > $web; 
	logdata='Success_Creating_Snapshot:'$hostnam/$DG/$FileS@$name;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Snap1030@@@$hostnam/$DG/$FileS@$name`;
echo Snap1030@$datenow@$timenow@$hostnam/$DG/$FileS@$name > ${logging}2
fi;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
fi
