#!/usr/local/bin/zsh
web='/var/www/html/des20/Data/Snapsstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
rm txt/cronthis.txt
stime=`echo $@ | awk '{print $1}'`;
hr=`echo $stime | awk -F: '{print $1}'`;
min=`echo $stime | awk -F: '{print $2}'`;
every=`echo $@ | awk '{print $2}'` ;
k=0; keep=`echo $@ | awk '{print $3}'`; keep=$(($keep+$k)); if (($keep < 1)); then keep=1; fi
pDG=` echo $@ | awk '{print $4}'`; 
FileS=` echo $@ | awk '{print $5}'`;
userreq=` echo $@ | awk '{print $6}'`;
txtres=txt/`basename $0`$userreq.txt
rm $txtres 2>/dev/null
DG=` echo $pDG | awk -F_ '{print $2}'`;
hostnam=` echo $pDG | awk -F_ '{print $1}'`;
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
echo Snap1019:Weekly.$hr.$min.$every.$keep/$hostnam/$DG/$FileS > $web;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Creating_WeeklyPreiod:'$hostnam/$DG/$FileS;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Snap1031@@@Weekly.$hr.$min.$every.$keep/$hostnam/$DG/$FileS`;
echo Snap1031@$datenow@$timenow@Weekly.$hr.$min.$every.$keep/$DG/$FileS > ${logging}2
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
stamp=`date +%s`;
crontab -l > txt/cronthis.txt
echo $min  $hr "*" "*" $every  /TopStor/pump.sh Snapshotnowhost $DG/$FileS Weekly.$keep.$hr.$min.$every $stamp 2>txt/SnapshotnowSystem.txt >> txt/cronthis.txt
crontab txt/cronthis.txt 2>> $txtres
err=`wc -c  $txtres | awk '{print $1}'`;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
if [[ $err -ge  4  ]]; then
	echo Snap1020:Weekly.$hr.$min.$every.$keep/$hostnam/$DG/$FileS > $web;
	cat $txtres > ${web}internal;
	logdata='Failed_Creating_WeeklyPeriod:'$hostnam/$DG/$FileS;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg error user $userreq data $logdata code Snap1032@@@Weekly.$hr.$min.$every.$keep/$hostnam/$DG/$FileS`;
echo Snap1032@$datenow@$timenow@Weekly.$hr.$min.$every.$keep/$hostnma/$DG/$FileS > ${logging}2
else 
	echo Snap1021:Weekly.$hr.$min.$every.$keep:$hostnam/$DG/$FileS > $web; 
	logdata='Success_Creating_WeeklyPeriod:'$hostnam/$DG/$FileS;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Snap1033@@@Weekly.$hr.$min.$every.$keep/$hostnam/$DG/$FileS`;
echo Snap1033@$datenow@$timenow@Weekly.$hr.$min.$every.$keep/$hostnam/$DG/$FileS > ${logging}2

fi;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
./GetPoolperiodlist 
fi
