#!/usr/local/bin/zsh
web='/usr/local/www/apache24/data/des19/Data/Snapsstatus.log';
logging='/usr/local/www/apache24/data/des19/Data/currentinfo2.log'
min=`echo $@ | awk '{print $1}'` ;
every=0; ev=`echo $@ | awk '{print $2}'`; every=$(($every+$ev)); if (($every < 1)); then every=1; fi
keep=0; k=`echo $@ | awk '{print $3}'`; keep=$(($keep+$k)); if (($keep < 1)); then keep=1 ; fi
DG=` echo $@ | awk '{print $4}'`; 
FileS=` echo $@ | awk '{print $5}'`;
userreq=` echo $@ | awk '{print $6}'`;
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
echo Snap1009: > $web;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Creating_HourlyPeriod:'$DG/$FileS@$name;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
crontab -l > txt/cronthis.txt
echo $min  "*"/$every "*" "*" "*"  /TopStor/pump.sh Snapshotnow $DG/$FileS hourly.$keep.$min.$every.na 2> txt/err.txt >> txt/cronthis.txt
crontab txt/cronthis.txt 2>>txt/${0:2}$userreq.txt
err=`wc -c  txt/${0:2}$userreq.txt | awk '{print $1}'`;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
if [[ $err -ge  4  ]]; then
	echo Snap1010: > $web;
	cat txt/${0:2}$userreq.txt > $web{internal};
	logdata='Failed_Creating_HourlyPeriod:'$DG/$FileS@$name;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg error user $userreq data $logdata`;
else 
 	echo Snap1011:hourly.$min.$every.$keep > $web; 
	logdata='Success_Creating_HourlyPeriod:'$DG/$FileS@$name;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
fi
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
rm txt/${0:2}$userreq.txt
./GetPoolperiodlist
fi
bb=`cat $web`;
echo $datenow $timenow :$bb > ${logging}2
