#! /usr/local/bin/zsh
cd /TopStor
web='/usr/local/www/apache24/data/des19/Data/statusglobal.log';
logging='/usr/local/www/apache24/data/des19/Data/currentinfo2.log'
cronout='txt/cronoutput.log'
echo creating Snapshot $@.... > $web;
oper=$@; 
echo oper=$oper > $cronout
oper1=`echo $oper | awk '{print $1}'`;
oper2=`echo $oper | awk '{print $2}'`;
echo oper1=$oper1 >> $cronout;
echo oper2=$oper2 >> $cronout;
stamp=`date +%s`;
echo stamp=$stamp >> $cronout
keep=`echo $oper2 | awk -F. '{print $2}'`;
echo keep=$keep >> $cronout
currentsnaps=`/sbin/zfs list -t snapshot | grep Data | grep "$oper2" | awk '{print $1}'`;
echo currentsnaps=$currentsnaps >> $cronout
oldsnap=`echo $currentsnaps | sort | head -n 1` ;
echo oldsnap=$oldsnap >> $cronout
count=0
countsnap=`echo  "$currentsnaps" | wc -l `;
echo countsnap=$countsnap >> $cronout 
countsnap=$(($countsnap+1));
echo countsnapplus=$countsnap >> $cronout
keep=$(($keep+0));
echo keeppluszero=$keep >> $cronout
timenow=`date`;
userreq='System';
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
if (( $countsnap >  $keep )); then 
	echo $timenow: have to delete $oldsnap >> $web;
        	logdata='Deleting_Snapshot:'$oldsnap;
        	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
		oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
	/sbin/zfs destroy $oldsnap 2>txt/$0$userreq.txt
	err=`wc -c  txt/$0$userreq.txt | awk '{print $1}'`;
	datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
	if [[ $err -ge  4  ]]; then
        	cat txt/$0$userreq.txt >> $web;
        	logdata='Difficulty_Deleting_Snapshot:'$oldsnap;
        	logthis=`./jsonthis3.sh Date $datenow time $timenow msg warning user $userreq data $logdata`;
        echo $logthis >> $cronout
	else
        	echo $timenow: DONE...Snapshot $@ is created >> $web;
        	logdata='Success_Deleting_Snapshot:'$oldsnap;
        	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
        	echo $logthis >> $cronout
	fi;
	oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
fi
newsnap2=`echo $oper2.$stamp`;
echo newsnap2=$newsnap2 >> $cronout
newsnap=`echo $oper1@$newsnap2`;
echo newsnap=$newsnap >> $cronout
logdata='Creating_Snapshot:'$newsnap;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
/sbin/zfs snapshot $newsnap &>txt/$0$userreq.txt
err=`wc -c  txt/$0$userreq.txt | awk '{print $1}'`;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
if [[ $err -ge  4  ]]; then
	cat txt/$0$userreq.txt >> $web;
	logdata='Failed_Creating_Snapshot:'$newsnap;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg error user $userreq data $logdata`;
	echo $logthis >> $cronout
else 
	echo $timenow: DONE...Snapshot $@ is created >> $web; 
	logdata='Success_Creating_Snapshot:'$newsnap;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
	echo $logthis >> $cronout
fi;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
rm txt/$0$userreq.txt
./GetSnaplist
