#!/bin/bash
echo $@ > /root/unixdeluser
export ETCDCTL_API=3
cd /TopStor
leaderip=`echo $@  | awk '{print $1}'`;
userreq=`echo $@  | awk '{print $2}'`;
pool=`echo $@  | awk '{print $3}'`;
volume=`echo $@  | awk '{print $4}'`;
ipaddr=`echo $@  | awk '{print $5}'`;
username=`echo $@ | awk '{print $6}'`;
docker exec etcdclient /TopStor/logmsg.py Tenantst02 info $userreq $username $volume 
sed -i "/$username/d" /$pool'/user_'$ipaddr
sed -i "s/,$username//g" /$pool'/group_'$ipaddr
sed -i "s/:$username/:/g" /$pool'/group_'$ipaddr
sed -i  "/$username/d" /$pool'/group_'$ipaddr
docker exec $container cat /etc/passwd | grep $username
if [ $? -ne 0 ];
then	
	docker exec etcdclient /TopStor/logmsg.py Tenantsu02 info $userreq $username $volume 
else
	docker exec etcdclient /TopStor/logmsg.py Tenantfa02 error $userreq $username $volume 
fi
/TopStor/TenantUserList $leaderip $volume $pool
