#!/usr/local/bin/zsh
web="/usr/local/www/apache24/data/des19/Data/Usersstatus.log";
logging="/usr/local/www/apache24/data/des19/Data/currentinfo2.log";
username=`echo $@ | awk '{print $1}'`;
userreq=`echo $@ | awk '{print $2}'`;
privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
echo Deleting user $username...> $web;
datenow=`date +%m/%d/%Y`;timenow=`date +%T`;
logdata='Deleting_user:'$username;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info data $logdata user $userreq`;
oldlog=`cat $logging | sed 's/]//g' `; newlog=$oldlog,$logthis]; echo $newlog > $logging;
/usr/local/bin/smbpasswd -d $username;
pw user del $username -r  2>txt/${0:2}$userreq.txt;
rm -R  /Data/Common/$username;
rm key/$username;
echo DONE..user $username is deleted > $web;
err=`wc -c txt/${0:2}$userreq.txt | awk '{print $1}'`;
if [[ $err -ge 3 ]]; then
	cat txt/${0:2}$userreq.txt > $web;
 	logdata='failed_deleting_user:'$username	;
else
	logdata='success_deleting_user:'$username;
fi;
datenow=`date +%m/%d/%Y`;timenow=`date +%T`;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info data $logdata user $userreq`;
oldlog=`cat $logging | sed 's/]//g' `; newlog=$oldlog,$logthis]; echo $newlog > $logging;
./UnisListUsers;
fi
rm txt/${0:2}$userreq.txt
bb=`cat $web`;
echo $datenow $timenow :$bb > ${logging}2
