#!/bin/bash
echo $@ > /root/unixadduser
export ETCDCTL_API=3
cd /TopStor
leaderip=`echo $@  | awk '{print $1}'`;
username=`echo $@ | awk '{print $2}'`;
homePool=`echo $@ | awk '{print $3}'`;
usergroups=`echo $@ | awk  '{print $4}'`;
grps=`echo $grpusers | sed 's/groups//g' | sed 's/\,/ /g'`
userpass=`echo $@ | awk '{print $5}'`;
size=`echo $@ | awk '{print $6}'`;
HomeAddr=`echo $@  | awk '{print $7}' `;
HomeSubnet=`echo $@  | awk '{print $8}'`;
pullsync=`echo $@  | awk '{print $9}'`;
echo $pullsync | grep pull
if [ $? -eq 0 ]
then
	userid=`echo $@  | awk '{print $10}'`;
	usergd=`echo $@  | awk '{print $11}'`;
	active=`echo $@  | awk '{print $12}'`;
	permis=`echo $@  | awk '{print $13}'`;
	userpass=`/TopStor/decthis.sh $username $userpass | awk -F'_result' '{print $2}'`
	userreq=`echo $@  | awk '{print $14}'`;
else
	userreq=`echo $@  | awk '{print $10}'`;
fi
# Guards for a NEW user (not for the sync copy another node makes of an accepted user): the rules of
# uservalid.py, and never a name that is a system account here -- "userdel -f" below would delete it.
echo $pullsync | grep -q pull
if [ $? -ne 0 ]
then
	why=`/TopStor/uservalid.py "$username" "$userpass"`
	if [ $? -ne 0 ]
	then
		echo UnixAddUser: user "$username" rejected: $why
		docker exec etcdclient /TopStor/logmsg.py `echo "$why" | cut -d'|' -f1` error $userreq `echo "$username" | cut -c1-32 | tr -c 'A-Za-z0-9.\n-' '.'`
		exit 1
	fi
	sysline=`getent passwd "$username"`
	if [ -n "$sysline" ]
	then
		echo "$sysline" | awk -F':' '{print $5}' | grep -q '^TopStor'
		if [ $? -ne 0 ]
		then
			echo UnixAddUser: user "$username" rejected: it is a system account on this node
			docker exec etcdclient /TopStor/logmsg.py Unlin1027rs error $userreq $username
			exit 1
		fi
	fi
fi
privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;
echo contrun $contrun, $userreq
if [[ $contrun == 'true' ]]
then

	myhost=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternode`
	myhostip=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternodeip`
	leader=`docker exec etcdclient /TopStor/etcdgetlocal.py leader`
	docker exec etcdclient /TopStor/logqueue.py `basename "$0"` running $userreq
	echo $leader | grep $myhost
	if [ $? -ne 0 ];
	then
 		etcd=$myhostip
	else
 		etcd=$leaderip
		echo $pullsync | grep pullsync
		if [ $? -ne 0 ]
		then
 
 			/pace/etcdget.py $etcd volumes --prefix | grep -w $username
	 		if [ $? -eq 0 ];
 			then
 				docker exec etcdclient /TopStor/logmsg.py Unlin1021uv warning $userreq $username
  				docker exec etcdclient/TopStor/logqueue.py `basename "$0"` finish $userreq 
  				exit
 			fi
		
 			./etcdget.py $etcd user --prefix | grep -w $username 
 			if [ $? -eq 0 ];
 			then
  				docker exec etcdclient /TopStor/logmsg.py Unlin1021uu warning $userreq $username
  				docker exec etcdclient /TopStor/logqueue.py `basename "$0"` finish $userreq 
  				exit
 			fi
		fi
	fi

 echo $pullsync | grep pull
 if [ $? -ne 0 ]
 then
	 docker exec etcdclient /TopStor/logmsg.py Unlin1018 info $userreq $username
 else
 	docker exec etcdclient /TopStor/logmsg.py Unlin1005 info $userreq $username
 fi
 userdel -f  $username
 #pas=`echo $userpass | openssl enc -e -base64 -aes-256-ctr -nopad -nosalt -k '#skMe22'$username`
 pas=`/TopStor/encthis.sh $username $userpass | awk -F'_result' '{print $2}'` 
 homebase='-b /NoHome -M'
 groupdel $username
 echo $homePool | grep 'NoHome'
 if [ $? -ne 0 ];
 then
  	homedir=$homePool
  	homebase='-b /'$homedir' -M'  
 else
 	echo $pullsync | grep pull
 	if [ $? -ne 0 ]
	then
  		docker exec etcdclient /TopStor/logmsg.py Unlin1023 warning $userreq $username
	fi
 fi
 echo iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii
 echo $pullsync | grep pull
 if [ $? -eq 0 ]
 then
	useradd -c"TopStor"$pas  $homebase -u $userid -p $userpass -s /usr/sbin/nologin $username
	groupmod -g $usergd $username
	echo useradd \-c"TopStor"$userpass $homebase \-g $usergd \-u $userid \-p $userpass \-s /usr/sbin/nologin $username
	
 else
	echo useradd \-c"TopStor"$pas $homebase \-p $userpass \-s /usr/sbin/nologin $username
 	useradd -c"TopStor"$pas $homebase -p $userpass -s /usr/sbin/nologin $username 
 fi
 echo $pullsync | grep pull
 if [ $? -ne 0 ]
 then
 	echo $homePool | grep 'NoHome'
 	if [ $? -ne 0 ];
 	then
		docker exec etcdclient docker exec etcdclient /TopStor/logmsg.py Unlin1024 info  $userreq $username $homedir
  		echo hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
  		echo /TopStor/VolumeCreateHOME $leaderip $homePool $username $size $username $HomeAddr $HomeSubnet active $userreq $myhost $userreq 
  		/TopStor/VolumeCreateHOME $leaderip $homePool $username $size $username $HomeAddr $HomeSubnet active $userreq $myhost $userreq 
  		echo hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
	fi
 fi

 # the leader does not run UnixAddUser_sync, which is what copies this script; the share containers read it from /hostetc
 cp -f /TopStor/smbuserfix.sh /etc/smbuserfix.sh
 currentcifs=`docker ps | awk '{print $NF}' | grep CIFS | grep -v 'CIFS_'`
 echo "$currentcifs" | while read y
 do
 	echo $y | grep CIFS
 	if [ $? -eq 0 ]
 	then
       		echo dock=$y
       		echo docker exec $y  sh /hostetc/smbuserfix.sh x $username $pas 
       		docker exec $y  sh /hostetc/smbuserfix.sh x $username $pas
 	fi	
 done

# echo $pullsync | grep sync 
# if [ $? -ne 0 ]
# then
# 	currentcifs=`docker ps | egrep 'CIFS|HOM' | awk '{print $1}' | grep -v 'CIFS_'`
# 	echo "$currentcifs" | while read y; do docker exec $y  sh /hostetc/smbuserfix.sh x $username $userpass;  done; 
# fi
 docker exec intsmb /root/smbuser.sh $username $userpass
 userline=`cat /etc/passwd | grep $username`
 if [ $? -ne  0  ]; then
 	echo $pullsync | grep pull
 	if [ $? -ne 0 ]
	then
  		docker exec etcdclient /TopStor/logmsg.py Unlin1020 error $userreq $username
	fi
 else 
 # openssl rsautl -encrypt -inkey key/public_key.pem -pubin -in <( echo $userpass) -out key/$username;  
  userid=`echo $userline | awk -F':' '{print $3}'`
  usergd=`echo $userline | awk -F':' '{print $4}'`
  userhome=`echo $userline | awk -F':' '{print $6}'`
  #userhash=`echo $userline | awk -F':' '{print $5}' | awk -F'TopStor' '{print $2}'`
  userhash=$pas
  
  /TopStor/etcdput.py $etcd 'usersinfo/'$username $userid':'$usergd':/'$homePool'/'$username'/'$size'/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no'
  /TopStor/etcdput.py $etcd 'usershash/'$username $userhash
  #/TopStor/broadcast.py UserAdd /TopStor/pump.sh UnixAddUser_sync -d$myhost $username $userhash $userid $usergd $userhome
  echo $etcd 2222222222222222222222222222222222222222222222222222222222222222 
   /TopStor/UnixChangeUser $leaderip $username $usergroups $userreq create $pullsync
  echo $etcd 2222222222222222222222222222222222222222222222222222222222222222 
  echo s$pullsync | grep pull
  if [ $? -ne 0 ]
  then
  	docker exec etcdclient /TopStor/logmsg.py Unlin1022 info $userreq $username
  fi
 fi 
 echo hi1
 echo myhost=$myhost    leader=$leader
 echo $leader | grep $myhost
 if [ $? -eq 0 ];
 then
	echo hi2
	stamp=`date +%s%N`
	myscript=`basename "$0"`
	params=`echo $myscript $@ $stamp | sed 's\ \\_\g'`
	/pace/etcddel.py $leaderip sync/user _${username}_
	/pace/etcdput.py $leaderip sync/user/$params/request/$myhost user_${username}_$stamp
	/pace/etcdput.py $leaderip sync/user/$params/request user_${username}_$stamp
	# the UsrChange request of this user (its groups) is filed by the UnixChangeUser call above, with the arguments of UnixChangeUser;
	# the copy that used to be filed here carried the arguments of UnixAddUser ($@), so followers ran UnixChangeUser with
	# 'NoHome' as the groups and 'groups...' as the requester
 fi
 echo hi3
 docker exec etcdclient /TopStor/logqueue.py `basename "$0"` finish $userreq 
fi
