#! /usr/local/bin/zsh
web='/usr/local/www/apache24/data/des19/Data/status.log';
resulting="not found";
username=`echo $@ | awk '{print $1}'`;
userchk=`echo $@ | awk '{print $2}'`;
if [[ -a key/$username ]]; then 
 pass1=`openssl rsautl -decrypt -inkey key/private_key.pem -in key/$username`;
 pass2=`openssl rsautl -decrypt -inkey key/private_key.pem -in key/$username$userchk`;
 if [[ $pass2 == $pass1 ]]; then
  resulting="success";
 fi;
fi;
echo $resulting

