#!/usr/local/bin/zsh
cd /TopStor;
web='/var/www/html/des20/Data/isuser.txt';
resulting="not found";
username=`echo $@ | awk '{print $1}'`;
userchk=`echo $@ | awk '{print $2}'`;
if [[ -a key/$username ]]; then 
 pass1=`openssl rsautl -decrypt -inkey key/private_key.pem -in key/$username`;
 pass2=`openssl rsautl -decrypt -inkey key/private_key.pem -in key/$username$userchk`;
 if [[ $pass2 == $pass1 ]]; then
  resulting="ok";
 fi;
fi;
resform=`/usr/local/bin/zsh jsonthis3.sh name $username status $resulting`;
echo $resform >$web 2>txt/err.txt

