#! /usr/local/bin/zsh
web='/usr/local/www/apache24/data/des19/Data/status.log';
logging='/usr/local/www/apache24/data/des19/Data/currentinfo2.log';
rm txt/err; 
echo Adding user.... > $web;
username=`echo $@ | awk '{print $1}'`;
userpass=`echo $@ | awk '{print $2}'`;
userreq=`echo $@  | awk '{print $3}'`;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='adding_user:'$username;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging
cp txt/logthis.log $logging; rm txt/logthis.log;
( echo $userpass | pw useradd  $username -m -h 0 -c "TopStor" -s /usr/sbin/nologin) 2> txt/err.txt;
( echo $userpass; echo $userpass) | /usr/local/bin/smbpasswd -s -a $username 2>> txt/err.txt;
mkdir /Data/Common/$username;
chown $username /Data/Common/$username;
err=`wc -c  txt/err.txt | awk '{print $1}'`;
if [[ $err >  4  ]]; then
	cat txt/err.txt > $web;
	errdata=`faile_adding_user:`$username;
	datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg error user $userreq data $errdata`
else 
 openssl rsautl -encrypt -inkey key/public_key.pem -pubin -in <( echo $userpass) -out key/$username;  
 chmod 400 key/$username;
 echo DONE...user $username is added > $web; 
 datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
 logdata='success_adding_user:'$username;
 logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data "$logdata"`;
fi 
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging
./UnixListUsers;
