#! /usr/local/bin/zsh
web='/usr/local/www/apache24/data/des19/Data/Usersstatus.log';
logging='/usr/local/www/apache24/data/des19/Data/currentinfo2.log';
echo Adding user.... > $web;
username=`echo $@ | awk '{print $1}'`;
userpass=`echo $@ | awk '{print $2}'`;
userreq=`echo $@  | awk '{print $3}'`;
echo $ussername, $userpass _ $userreq > tmpnow
privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='adding_user:'$username;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging
( echo $userpass | pw useradd  $username -m -h 0 -c "TopStor" -s /usr/sbin/nologin) 2> txt/$0$userreq.txt;
( echo $userpass; echo $userpass) | /usr/local/bin/smbpasswd -s -a $username 2>> txt/$0$userreq.txt;
mkdir /Data/Common/$username;
chown $username /Data/Common/$username;
err=`wc -c  txt/$0$userreq.txt | awk '{print $1}'`;
if [[ $err -ge  4  ]]; then
	cat txt/$0$userreq.txt > $web;
	errdata=`faile_adding_user:`$username;
	datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg error user $userreq data $errdata`
else 
 openssl rsautl -encrypt -inkey key/public_key.pem -pubin -in <( echo $userpass) -out key/$username;  
 chmod 400 key/$username;
 echo DONE...user $username is added > $web; 
 datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
 logdata='success_adding_user:'$username;
 logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data "$logdata"`;
fi 
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging
./UnixListUsers;
fi
rm txt/$0$userreq.txt;
bb=`cat $web`;
echo $datenow $timenow :$bb > ${logging}2
