#! /usr/local/bin/zsh
cd /TopStor/;
webusers='/usr/local/www/apache24/data/des19/Data/listusers.txt';
namearray=( `cat /etc/passwd | grep TopStor | /usr/bin/cut -d: -f1,3 | /usr/bin/cut -d: -f1 | grep -v moataz ` ); 
nameforjson=`echo $namearray | /usr/bin/sed 's/ /:/g'` ;
jsonname=`./jsonthis.sh $nameforjson`;
echo $jsonname >$webusers ;
