#! /usr/local/bin/zsh
web='/usr/local/www/apache24/data/des19/Data/status.log';
logging='/usr/local/www/apache24/data/des19/Data/currentinfo2.log'
echo Creating  Volume .... > $web;
name=`echo $@ | awk '{print $2}'`;
DG=`echo $@ | awk '{print $1}'`;
quota=`echo $@ | awk '{print $3}'`;
userreq=` echo $@ | awk '{print $4}'`;
privilege="CIFS";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Creating_Volume:'$DG/$name;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging; 
/sbin/zfs create -o quota=$quota -o dedup=on -o compression=on  $DG/$name 2> txt/$0$userreq.txt 
/sbin/zfs set prot:kind=CIFS $DG/$name
sed -e "s/NAMECIFS/$name/g" sharecifs.txt > $name.txt;
cat $name.txt >> smb4.conf;
cp smb4.conf /usr/local/etc/
service samba_server reload;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
err=`wc -c  txt/$0$userreq.txt | awk '{print $1}'`;
if [[ $err >  4  ]]; then
	cat txt/$0$userreq.txt > $web;
	logdata='Failed_Creating__Volume:'$DG/$name;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg error user $userreq data $logdata`;
else 
 echo DONE...Volume $DG/$name is created > $web; 
	logdata='success_Creating__Volume:'$DG/$name;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
fi;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging; 
rm txt/$0$userreq.txt
./GetPoolVollist
fi
