#!/bin/sh
cd /TopStor
export ETCDCTL_API=3
echo $@ > /root/VolumeDeleteISCSI 
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
volname=`echo $@ | awk '{print $3}'`;
leaderip=`echo $@ | awk '{print $1}'`;
pDG=`echo $@ | awk '{print $2}'`;
pro=`echo $@ | awk '{print $4}'`;
userreq=` echo $@ | awk '{print $5}'`;
DG=`echo $pDG `;
privilege=$pro;
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
	myhost=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternode`
	myhostip=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternodeip`
	leader=`docker exec etcdclient /TopStor/etcdgetlocal.py leader`
	echo $leader | grep $myhost
	if [ $? -ne 0 ];
	then
 		etcd=$myhostip
	else
 		etcd=$leaderip
 	fi


  docker exec etcdclient /TopStor/logmsg.py ISCSI1000 info $userreq $volname
 cd /TopStor
 echo $DG/$volname
 # container flavour: no udev, the zvol node and link are made here (QSD5.242)
 [ -f /TopStor/flavor.sh ] && . /TopStor/flavor.sh
 is_container 2>/dev/null && /pace/czvoldev.sh
 # the address of the target, read before the volume's files are removed
 iscsisum=`grep SUMMARY /$DG/iscsi.$volname 2>/dev/null | head -1`
 iscsiip=`echo $iscsisum | awk -F'/' '{print $3}'`
 iscsisub=`echo $iscsisum | awk -F'/' '{print $4}'`
 disk=`ls -l /dev/zvol/$DG/$volname | awk -F'/' '{print $NF}'`
 echo $disk
 echo targetcli backstores/block delete ${disk}-${myhost}-$volname
 targetcli backstores/block delete ${disk}-${myhost}-$volname
 /sbin/zfs destroy -rf $DG/$volname 
 if [ $? -ne 0  ]; then
   docker exec etcdclient /TopStor/logmsg.py ISCSI1001 error $userreq $volname
   echo /sbin/zfs destroy -rf $DG/$volname >/root/errorVolumeDeleteISCSI
 else
  rm -rf /$DG/iscsi.$volname /TopStordata/iscsi.$volname
  /pace/etcddel.py $leaderip volume $volname
  # QSD5.242: the target of the address (iqn.2016-03.com.<ip without dots>:data) and the address itself stay behind when
  # the last LUN of the target is gone; remove both, otherwise the target is still discoverable and the address still answers
  if [ -n "$iscsiip" ]
  then
   ipdom=`echo $iscsiip | sed 's/\.//g'`
   if ! targetcli ls /iscsi/iqn.2016-03.com.$ipdom:data/tpg1/luns 2>/dev/null | grep -q 'o- lun[0-9]'
   then
    targetcli /iscsi delete iqn.2016-03.com.$ipdom:data
    targetcli saveconfig
    nmcli conn mod cmynode -ipv4.addresses ${iscsiip}/${iscsisub:-24}
    nmcli conn up cmynode
   fi
  fi
  stamp=`date +%s`
  ETCDCTL_API=3 /pace/etcdput.py $leaderip sync/volumes/${DG}_$name/request volumes_$stamp
  ETCDCTL_API=3 /pace/etcdput.py $leaderip sync/volumes/${DG}_$name/request/$leader volumes_$stamp
  /TopStor/SnapShotPeriodDelete $leaderip $volname $userreq
  #/pace/delbroadcastlocal.py volume $volname
  /pace/putzpool.py $leaderip
  docker exec etcdclient /TopStor/etcdputlocal.py dirty/volume 0
  docker exec etcdclient /TopStor/logmsg.py ISCSI1002 info  $userreq $volname
 fi
 rm -rf /$DG/iscsi.$volname
fi
