#! /usr/local/bin/zsh
cd /TopStor
web='/usr/local/www/apache24/data/des19/Data/status.log';
echo Deleteing  $@.... > $web;
echo started > txt/VollCreate.txt
rm txt/err.txt;
volname=`echo $@ | awk '{print $2}'`;
DG=`echo $@ | awk '{print $1}'`;
/sbin/zfs destroy $DG/$volname  2>txt/err.txt;
err=`wc -c  txt/err.txt | awk '{print $1}'`;
if [[ $err >  4  ]]; then
	cat txt/err.txt > $web;
else 
 echo DONE...volume $volname is deleted > $web; 
fi;
./GetPoolVollist
