#!/usr/local/bin/zsh
cd /TopStor/
web='/var/www/html/des20/Data/CIFSstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
runningpools='/pacedata/pools/runningpools'
name=`echo $@ | awk '{print $2}'`;
pDG=`echo $@ | awk '{print $1}'`;
quota=`echo $@ | awk '{print $3}'`;
userreq=` echo $@ | awk '{print $4}'`;
DG=`echo $pDG | awk -F_ '{print $2}'`;
hostnam=`echo $pDG | awk -F_ '{print $1}'`;
sshost=`cat $runningpools | grep $hostnam | awk '{print $1}'`;
echo CIFS1001:$hostnam/$DG/$name > $web;
privilege="CIFS";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
oldname=` ssh $sshost /sbin/zfs list | grep -w "$name" | wc -c `;
if [[ $oldname -ge 4 ]];
then 
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Creating_Volume:'$DG/$name'already_there';
logthis=`./jsonthis3.sh Date $datenow time $timenow msg warning user $userreq data $logdata code NFS1004@@@$hostnam/$DG/$name`;
echo NFS1004@$datenow@$timenow@$hostnam/$DG/$name > ${logging}2
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging; 
echo CIFS1002:$hostnam/$DG/$name > $web;
else
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Creating_Volume:'$hostnam/$DG/$name;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code NFS1004@@@$DG/$name`;
echo NFS1004@$datenow@$timenow@$hostnam/$DG/$name > ${logging}2
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging; 
g=`ssh $sshost cat /TopStor/smb.confcurrent | grep ${name}_only | wc -c`; 
if [[ g -ge 4 ]];
then
 datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
 logdata='Creating_Volume_already_there:'$hostnam/$DG/$name ;
 logthis=`./jsonthis3.sh Date $datenow time $timenow msg warning user $userreq data $logdata code NFS1005@@@$hostnam/$DG/$name`;
echo NFS1005@$datenow@$timenow@$hostnam/$DG/$name > ${logging}2
 oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging; 
else
ssh $sshost " cd /TopStor &&
 /sbin/zfs create -o quota=$quota -o dedup=on -o compression=lz4  $DG/$name 2> txt/${0:2}$userreq.txt  &&
 /sbin/zfs set prot:kind=CIFS $DG/$name &&
 cp /etc/samba/smb.conf /TopStor/smb.confcurrent &&
 cp sharecifs.txt $name.txt
 sed -i "s/NAMECIFS/$name/g"  $name.txt &&
 sed -i "s/POOL/$DG/g" $name.txt &&
 cat $name.txt >> smb.confcurrent &&
 cat $name.txt >> CIFSshares.txt &&
 cat $name.txt >> /etc/samba/smb.conf &&
 chmod 777 /$DG/$name
 systemctl stop smb &&
 systemctl start smb " 
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
err=`wc -c  txt/${0:2}$userreq.txt | awk '{print $1}'`;
if [[ $err -ge  4  ]]; then
	echo CIFS1003:$hostnam/$DG/$name > $web;
	cat txt/${0:2}$userreq.txt > ${web}internal;
	logdata='Failed_Creating__Volume:'$hostnam/$DG/$name;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg error user $userreq data $logdata code NFS1005@@@i$hostnam/$DG/$name`;
echo NFS1005@$datenow@$timenow@$hostnam/$DG/$name > ${logging}2
else 
 echo CIFS1004:$hostnam/$DG/$name > $web; 
	logdata='success_Creating__Volume:'$hostnam/$DG/$name;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code NFS1006@@@$hostnam/$DG/$name`;
echo NFS1006@$datenow@$timenow@$hostnam/$DG/$name > ${logging}2
fi;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging; 
rm txt/${0:2}$userreq.txt
./GetPoolVollist &>/dev/null
fi
fi
fi
echo ready ;
