#! /usr/local/bin/zsh
cd /TopStor
web='/usr/local/www/apache24/data/des19/Data/status.log';
logging='/usr/local/www/apache24/data/des19/Data/currentinfo2.log'
echo Deleteing  $@.... > $web;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
echo started > txt/VollCreate.txt
rm txt/err.txt;
volname=`echo $@ | awk '{print $2}'`;
DG=`echo $@ | awk '{print $1}'`;
userreq=` echo $@ | awk '{rint $3}'`;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Deleting:'$DG/$volname;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
/sbin/zfs destroy $DG/$volname  2>txt/err.txt;
err=`wc -c  txt/err.txt | awk '{print $1}'`;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
if [[ $err >  4  ]]; then
	cat txt/err.txt > $web;
	logdata=`failed_deleting_volume:'$DG/$volname;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
else 
 echo DONE...volume $volname is deleted > $web; 
 logdata='success_deleting_volume'$DG/$volname;
 logthis=`./jsonthis3.sh Date $datenow time $timenow msg error user $userreq data $logdata`;
fi;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
./GetPoolVollist
