#!/usr/local/bin/zsh
cd /TopStor
web='/var/www/html/des20/Data/CIFSstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
runningpools='/pacedata/pools/runningpools'
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
rm txt/err2.txt 2>/dev/null
volname=`echo $@ | awk '{print $2}'`;
pDG=`echo $@ | awk '{print $1}'`;
pro=`echo $@ | awk '{print $3}'`;
userreq=` echo $@ | awk '{print $4}'`;
DG=`echo $pDG | awk -F_ '{print $2}'`;
hostnam=`echo $pDG | awk -F_ '{print $1}'`;
sshost=`cat $runningpools | grep $hostnam | awk '{print $1}'`;
echo CIFS1005:$hostnam/$DG/$volname > $web;
privilege=$pro;
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Deleting:'$hostnam/$DG/$volname;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code NFS1000@@@$hostnam/$DG/$volname`;
echo NFS1000@$datenow@$timenow@$hostnam/$DG/$volname > ${logging}2
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
ssh $sshost " cd /TopStor &&
 /sbin/zfs destroy $DG/$volname"  &>txt/${0:2}$userreq.txt 
err=`wc -c  txt/${0:2}$userreq.txt | awk '{print $1}'`
err=$((err+1));
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
if [[ $err -ge  4  ]]; then
	echo CIFS1006:$hostnam/$DG/$volname > $web;
	cat txt/${0:2}$userreq.txt > ${web}internal;
	logdata='failed_deleting_volume:'$hostnam/$DG/$volname;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg error user $userreq data $logdata code NFS1001@@@$hostnam/$DG/$volname`;
echo NFS1001@$datenow@$timenow@$hostnam/$DG/$volname > ${logging}2
else 
cp /etc/samba/smb.conf smb.confcurrent;
 rm $volname.txt;
 ./delblock.sh start${volname}_only stop${volname}_only smb.confcurrent  ;
 ./delblock.sh start${volname}_only stop${volname}_only CIFSshares.txt  ;
 cp smb.confcurrent /etc/samba/smb.conf;
 systemctl restart smb
 echo CIFS1007:$hostnam/$DG/$volname > $web; 
 logdata='success_deleting_volume'$hostnam/$DG/$volname;
 logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code NFS1002@@@$hostnam/$DG/$volname`;
echo NFS1002@$datenow@$timenow@$hostnam/$DG/$volname > ${logging}2
fi;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
./GetPoolVollist
rm txt/${0:2}$userreq.txt
fi
