#!/usr/local/bin/zsh
web='/usr/local/www/apache24/data/des19/Data/NFSstatus.log';
logging='/usr/local/www/apache24/data/des19/Data/currentinfo2.log'
echo Creating  Volume .... > $web;
name=`echo $@ | awk '{print $2}'`;
DG=`echo $@ | awk '{print $1}'`;
quota=`echo $@ | awk '{print $3}'`;
userreq=` echo $@ | awk '{print $4}'`;
privilege="CIFS";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
oldname=` zfs list | grep -w "$name" | wc -c `;
if [[ $oldname -ge 4 ]];
then
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Creating_Volume:'$DG/$name'already_there';
logthis=`./jsonthis3.sh Date $datenow time $timenow msg warning user $userreq data $logdata`;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
echo Volume $name is already there > $web;
else
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Creating_Volume:'$DG/$name;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging; 
g=`cat /etc/exports | grep ${name}_only | wc -c`; if [[ g -ge 4 ]];
then
 datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
 logdata='Creating_Volume_already_there:'$DG/$name;
 logthis=`./jsonthis3.sh Date $datenow time $timenow msg warning user $userreq data $logdata`;
 oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging; 
else
/sbin/zfs create -o quota=$quota -o dedup=on -o compression=lz4  $DG/$name 2> txt/${0:2}$userreq.txt 
/sbin/zfs set prot:kind=NFS $DG/$name
echo \# start${name}_only >> /etc/exports
echo /$DG/$name >> /etc/exports
echo  \# stop${name}_only >> /etc/exports
service mountd restart > /dev/null 2>txt/${0:2}$userreq.txt 
service nfsd restart > /dev/null 2>>txt/${0:2}$userreq.txt
cat txt/${0:2}$userreq.txt | grep -v such > txt/${0:2}$userreq.txt
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
err=`wc -c  txt/${0:2}$userreq.txt | awk '{print $1}'`;
if [[ $err -ge  4  ]]; then
	cat txt/${0:2}$userreq.txt > $web;
	logdata='Failed_Creating__Volume:'$DG/$name;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg error user $userreq data $logdata`;
else 
 echo DONE...Volume $DG/$name is created > $web; 
	logdata='success_Creating__Volume:'$DG/$name;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
fi;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging; 
rm txt/${0:2}$userreq.txt
./GetPoolVollist
fi
fi
fi
bb=`cat $web`;
echo $datenow $timenow :$bb > ${logging}2
echo ready ;
