#!/usr/local/bin/zsh
cd /TopStor
web='/usr/local/www/apache24/data/des19/Data/NFSstatus.log';
logging='/usr/local/www/apache24/data/des19/Data/currentinfo2.log'
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
rm txt/err2.txt;
volname=`echo $@ | awk '{print $2}'`;
DG=`echo $@ | awk '{print $1}'`;
pro=`echo $@ | awk '{print $3}'`;
userreq=` echo $@ | awk '{print $4}'`;
echo CIFS1005:$DG/$volname > $web;
privilege=$pro;
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Deleting:'$DG/$volname;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
/sbin/zfs destroy $DG/$volname &>txt/${0:2}$userreq.txt;
err=`wc -c  txt/${0:2}$userreq.txt | awk '{print $1}'`;
err=$((err+1));
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
if [[ $err -ge  4  ]]; then
	echo CIFS1006:$DG/$volname > $web;
	cat txt/err2.txt > ${web}internal;
	logdata='failed_deleting_volume:'$DG/$volname;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg error user $userreq data $logdata`;
else 
 ./delblock.sh start${volname}_only stop${volname}_only /etc/exports  ;
 service nfsd restart;
 echo CIFS1007:$DG/$volname > $web; 
 logdata='success_deleting_volume'$DG/$volname;
 logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
fi;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
./GetPoolVollist
rm txt/${0:2}$userreq.txt
fi
bb=`cat $web`;
echo $datenow $timenow :$bb > ${logging}2
