#! /usr/local/bin/zsh
cd /TopStor
web='/usr/local/www/apache24/data/des19/Data/CIFSstatus.log';
logging='/usr/local/www/apache24/data/des19/Data/currentinfo2.log'
echo Deleteing  $@.... > $web;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
rm txt/err2.txt;
volname=`echo $@ | awk '{print $2}'`;
DG=`echo $@ | awk '{print $1}'`;
pro=`echo $@ | awk '{print $3}'`;
userreq=` echo $@ | awk '{print $4}'`;
privilege=$pro;
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Deleting:'$DG/$volname;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
/sbin/zfs destroy $DG/$volname &>txt/$0$userreq.txt;
err=`wc -c  txt/$0$userreq.txt | awk '{print $1}'`;
err=$((err+1));
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
if [[ $err -ge  4  ]]; then
	cat txt/$0$userreq.txt > $web;
	logdata='failed_deleting_volume:'$DG/$volname;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg error user $userreq data $logdata`;
else 
cp /usr/local/etc/smb4.conf smb4.confcurrent;
 rm $volname.txt;
 ./delblock.sh start${volname}_only stop${volname}_only smb4.confcurrent  ;
 ./delblock.sh start${volname}_only stop${volname}_only CIFSshares.txt  ;
 cp smb4.confcurrent /usr/local/etc/smb4.conf;
 service samba_server restart;
 echo DONE...volume $volname is deleted > $web; 
 logdata='success_deleting_volume'$DG/$volname;
 logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata`;
fi;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
./GetPoolVollist
rm txt/$0$userreq.txt
fi
bb=`cat $web`;
echo $datenow $timenow :$bb > ${logging}2
