#!/bin/sh
echo $@ >/root/volchangenfs
cd /TopStor
export ETCDCTL_API=3
leaderip=`echo $@ | awk '{print $1}'`;
pDG=`echo $@ | awk '{print $2}'`;
name=`echo $@ | awk '{print $3}'`;
quota=`echo $@ | awk '{print $4}'`;
writev=`echo $@ | awk '{print $5}'`;
ipaddr=`echo $@ | awk '{print $6}'`;
ipsubnet=`echo $@ | awk '{print $7}'`;
active=`echo $@ | awk '{print $8}'`;
myhost=`echo $@ | awk '{print $9}'`;
userreq=` echo $@ | awk '{print $10}'`;

DG=`echo $pDG `;
echo $@ > /root/VolChange
rm -rf $txtres 2>/dev.null
privilege="NFS";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 oct2=`echo $ipaddr | awk -F'.' '{print $2}'`
 oct3=`echo $ipaddr | awk -F'.' '{print $3}'`
 who='*'
 cips=`/pace/etcdget.py $leaderip vol --prefix``/pace/etcdget.py $leaderip Activ --prefix``/pace/etcdget.py $leaderip repl --prefix`
 echo $cips | grep $ipaddr
 if [ $? -eq 0 ];
 then
	/TopStor/logmsg.py IPadduqfa info $userreq
	exit
 fi
 ETCDCTL_API=3 /pace/etcdput.py $leaderip volumes/NFS/$myhost/$DG/$name $DG/$name/$who/rw/sync/insecure/no_root_squash/no_all_squash/$writev/$ipaddr/$ipsubnet/$active
  stamp=`date +%s`
  ETCDCTL_API=3 /pace/etcdput.py $leaderip sync/volumes/${DG}_$name/request volumes_$stamp
  ETCDCTL_API=3 /pace/etcdput.py $leaderip sync/volumes/${DG}_$name/request/$leader volumes_$stamp
 oldipaddr=`zfs get -H ip:addr $DG/$name | awk '{print $3}'`
 docker rm -f NFS-$ipaddr
 oldipsubnet=`zfs get -H ip:subnet $DG/$name | awk '{print $3}'`
 sed -i "s/$oldipaddr/$ipaddr/g" /$DG/exports.$name
 sed -i "s/$oldipsubnet/$ipsubnet/g" /$DG/exports.$name
 /sbin/zfs set ip:addr=$ipaddr $DG/$name
 /sbin/zfs set ip:subnet=$ipsubnet $DG/$name
 /sbin/zfs set status:mount=$active $DG/$name
 docker rm -f NFS-$ipaddr
/TopStor/logmsg.py VolCsu01 info $userreq $name
fi;
